from src.enum_types_constants import ControllerModes, ModcodModes, TdmaInputModes, RollofModes, TdmaModcod, \
    DemodulatorInputModes, ModelTypes

options = {
    'network': {
        'name': 'test_net',
        'dev_password': 'teste',
    },
    'teleport': {
        'name': 'test_tp',
        'tx_lo': '0',
        'rx1_lo': '0',
        'rx2_lo': '0',
    },
    'controller_MF': {
        'name': f'test_ctrl',
        'mode': ControllerModes.MF_HUB,
        'teleport': f'teleport:0',
        'Net_ID': '132',
        'uhp_model': ModelTypes.UHP200,
        'tx_frq': '960000',
        'tx_sr': '1500',
        'tx_modcod': ModcodModes.SF_QPSK_3_4,
        'tx_level': '42',
        'rx1_frq': '960000',
        'rx1_sr': '1500',
    },
    'controller_HBL': {
        'name': 'HL_test',
        'mode': ControllerModes.HUBLESS_MASTER,
        'teleport': 'teleport:0',  # default config must be loaded
        'uhp_model': ModelTypes.UHP200,
        'stn_number': 5,
        'frame_length': 128,
        'slot_length': 12,
        'tdma_input': TdmaInputModes.RX1,
        'tdma_sr': 2000,
        'tdma_roll': RollofModes.R20,
        'mf1_rx': 980000,
        'mf1_tx': 980000,
        'tdma_mc': TdmaModcod._8PSK_2_3,
        'tx_on': 1,
        'tx_level': 40,
        'rx1_input': DemodulatorInputModes.OFF,
    },
    'controller_DAMA': {
        'name': f'test_ctrl',
        'mode': ControllerModes.DAMA_HUB,
        'teleport': f'teleport:0',
        'Net_ID': '132',
        'uhp_model': ModelTypes.UHP200,
        'tx_frq': '960000',
        'tx_sr': '1000',
        'tx_modcod': ModcodModes.SF_QPSK_3_4,
        'tx_level': '42',
        'a_dama_tx_frq': '970000',
        'a_dama_rx_frq': '970000',
        'a_dama_sr': '2000',
        'a_dama_modcod': ModcodModes.SF_QPSK_3_4,
        'a_dama_tx': True,
        'a_dama_level': '42',
        'b_dama_tx_frq': '976000',
        'b_dama_rx_frq': '976000',
        'b_dama_sr': '1500',
        'b_dama_modcod': ModcodModes.SF_QPSK_2_3,
        'b_dama_tx': True,
        'b_dama_level': '42',
    },
    'DAMA_Inroute': {
        'name': f'dama_inr',
        'mode': ControllerModes.DAMA_INROUTE,
        'tx_controller': 'controller: 0',
        'teleport': f'teleport:0',
        'uhp_model': ModelTypes.UHP200,
        'b_dama_tx_frq': '980000',
        'b_dama_rx_frq': '980000',
        'b_dama_sr': '2000',
        'b_dama_modcod': ModcodModes.SF_QPSK_3_4,
        'b_dama_tx': True,
        'b_dama_level': '42',
    },
    'Outroute': {
        'name': f'test_ctrl_Out',
        'mode': ControllerModes.OUTROUTE,
        'teleport': f'teleport:0',
        'Net_ID': '137',
        'uhp_model': ModelTypes.UHP200,
        'tx_frq': '960000',
        'tx_sr': '1500',
        'tx_modcod': ModcodModes.SF_QPSK_3_4,
        'tx_level': '42',
        'rx1_frq': '960000',
        'rx1_sr': '1500',
    },
    'Inroute': {
        'name': f'test_ctrl_Inr',
        'mode': ControllerModes.INROUTE,
        'tx_controller': 'controller: 0',
        'teleport': f'teleport:0',
        'uhp_model': ModelTypes.UHP200,
        'stn_number': 5,
        'frame_length': 128,
        'slot_length': 10,
        'tdma_input': TdmaInputModes.RX1,
        'tdma_sr': 1000,
        'tdma_roll': RollofModes.R20,
        'mf1_rx': 1000000,
        'mf1_tx': 1000000,
        'tdma_mc': TdmaModcod._8PSK_2_3,
        'no_stn_check': '1',
    },
    'MfInroute': {
        'name': f'test_ctrl_MfInr',
        'mode': ControllerModes.MF_INROUTE,
        'teleport': f'teleport:0',
        'uhp_model': ModelTypes.UHP200,
        'Net_ID': '132',
    },
    'service': {
        'name': 'test_service'
    },
    'SR_controller': {
        'name': f'SR_test',
    },
    'SR_teleport': {
        'name': f'SR_teleport',
        'teleport': f'teleport:0',
    },
    'Device1': {
        'name': f'Device1',
        'mode': '2',
        'ip': '0.0.0.0',
        'mask': '/24',
        'gateway': '0.0.0.0',
        'dem2_connect': '1',
        'uhp_model': '2',
    },
    'Device2': {
        'name': f'Device2',
        'mode': '2',
        'ip': '0.0.0.0',
        'mask': '/24',
        'gateway': '0.0.0.0',
        'dem2_connect': '1',
        'uhp_model': '2',
    },
    'Device3': {
        'name': f'Device3',
        'mode': '2',
        'ip': '0.0.0.0',
        'mask': '/24',
        'gateway': '0.0.0.0',
        'dem2_connect': '1',
        'uhp_model': '2',
    },
    'lic_hub': {
        'name': 'lic_hub',
        'license_key': 'eyJvcHRpb25zIjoxNjMsInNpZ25hdHVyZSI6IjQ2QTFENzBFMDg0M0VCRDc5RjEyIn0=',
        'group1': '1',
    },
    'lic_inr': {
        'name': 'lic_inr',
        'license_key': 'eyJvcHRpb25zIjoyLCJzaWduYXR1cmUiOiJFQzgwQjVDNDg3RjlGN0I2OUU3MSJ9',
        'group2': '1',
    },
    'lic_dama_hub': {
        'name': 'lic_dama_hub',
        'license_key': 'eyJvcHRpb25zIjoxNDQwLCJzaWduYXR1cmUiOiJEM0YwMjkwNjRFM0I3QTI2RjcwRiJ9',
        'group1': '1',
    },
    'lic_hbl': {
        'name': 'lic_hbl',
        'license_key': 'eyJvcHRpb25zIjoyMDcyLCJzaWduYXR1cmUiOiJFREFEQTMxMkMxNDdGQkUzMTc4NyJ9',
        'group1': '1',
    },
    'lic_2dem': {
        'name': 'lic_2dem',
        'license_key': 'eyJvcHRpb25zIjoyNTYsInNpZ25hdHVyZSI6IkJDMTgyRUQ2QTAwQjYyNEU2MzZGIn0=',
        'group2': '1',
    },
}
