# constants.py - the module contains constants used in the UHP WEB interface, as well as some telnet constants

# Advanced->System->Interfaces form->Modulator queues (packets)
from src.enum_types_constants import CheckTypesStr, ActionTypesStr, ShaperUpQueueStr

P1_ATTR_NAME = 'dd'
P2_ATTR_NAME = 'de'
P3_ATTR_NAME = 'df'
P4_ATTR_NAME = 'dg'
P5_ATTR_NAME = 'dh'
P6_ATTR_NAME = 'di'
P7_ATTR_NAME = 'dj'
CTRL_ATTR_NAME = 'dk'

# Advanced->IP protocols->SNMP form
SNMP_VERSION_ATTR_NAME = 'dc'
SNMP_PRIV_MODE_ATTR_NAME = 'dd'
SNMP_ACCESS_IP1_ATTR_NAME = 'ia'
SNMP_ACCESS_IP2_ATTR_NAME = 'ib'
SNMP_READ_COMMUNITY_ATTR_NAME = 'tb'
SNMP_WRITE_COMMUNITY_ATTR_NAME = 'tc'
SNMP_USERNAME_ATTR_NAME = 'tf'
SNMP_AUTH_PASS_ATTR_NAME = 'td'
SNMP_PRIV_PASS_ATTR_NAME = 'te'

# Advanced->IP protocols->ARP form
ARP_TABLE_CLEAR_ATTR_NAME = 'da'
PROXY_ARP_ENABLE_ATTR_NAME = 'db'

# Advanced->IP protocols->TFTP form
TFTP_SERVER_IP_ATTR_NAME = 'ia'
TFTP_VLAN_ATTR_NAME = 'db'

# Advanced->IP protocols->NAT form
NAT_ENABLE_ATTR_NAME = 'di'
NAT_EXTERNAL_IP_ATTR_NAME = 'if'
NAT_INTERNAL_NETWORK_ATTR_NAME = 'ih'
NAT_INTERNAL_MASK_ATTR_NAME = 'mg'

# Advanced->IP protocols->RIPv2 form
RIP_ENABLE_ATTR_NAME = 'db'
RIP_UPDATE_ATTR_NAME = 'dc'
RIP_TIMEOUT_ATTR_NAME = 'dd'
RIP_COST_ATTR_NAME = 'de'
RIP_AUTH_ATTR_NAME = 'df'
RIP_PASS_AUTH_NAME = 'tg'

# Advanced->IP protocols->SNTP form
SNTP_MODE_ATTR_NAME = 'db'
SNTP_SERVER_IP_ATTR_NAME = 'ia'
SNTP_VLAN_ATTR_NAME = 'dc'

# Advanced->IP protocols->Multicast form
MULTICAST_MODE_ATTR_NAME = 'db'
MULTICAST_TIMEOUT_ATTR_NAME = 'da'

# Advanced->Network->Security form
ENCRYPTION_ATTR_NAME = 'db'
ENCRYPTION_KEY_ATTR_NAME = 'dc'

# Advanced->IP protocols->Acceleration form
TCPA_ENABLE_ATTR_NAME = 'da'
TCPA_VERSION_ATTR_NAME = 'dq'
TCPA_FROM_SVLAN_ATTR_NAME = 'dd'
TCPA_TO_SVLAN_ATTR_NAME = 'de'
TCPA_MSS_ATTR_NAME = 'db'
TCPA_MAX_WINDOW_ATTR_NAME = 'di'
TCPA_WINDOW_UPDATE_ATTR_NAME = 'dj'
TCPA_SESSIONS_ATTR_NAME = 'dh'
TCPA_BUF_COEF_ATTR_NAME = 'dc'
TCPA_MAX_PKTS_ATTR_NAME = 'dk'
TCPA_MAX_QLEN_ATTR_NAME = 'dl'
TCPA_RETRY_TIME_ATTR_NAME = 'dm'
TCPA_RETRIES_ATTR_NAME = 'dn'
TCPA_TIMEOUT_ATTR_NAME = 'do'
TCPA_ACK_PERIOD_ATTR_NAME = 'dp'

# Advanced->QoS->Service mon. form
SM_ENABLE_ATTR_NAME = 'dt'
SM_INTERVAL_ATTR_NAME = 'dk'
SM_LOSTS_ATTR_NAME = 'dl'
SM_POLL_ENABLE1_ATTR_NAME = 'da'
SM_POLL_IP1_ATTR_NAME = 'ig'
SM_POLL_VLAN1_ATTR_NAME = 'ds'
SM_CHK_DELAY1_ATTR_NAME = 'dc'
SM_MAX_DELAY1_ATTR_NAME = 'dh'
SM_POLL_ENABLE2_ATTR_NAME = 'db'
SM_POLL_IP2_ATTR_NAME = 'ii'
SM_POLL_VLAN2_ATTR_NAME = 'du'
SM_CHK_DELAY2_ATTR_NAME = 'dd'
SM_MAX_DELAY2_ATTR_NAME = 'dj'
SM_RX_CHECK_RATE_ATTR_NAME = 'dm'
SM_TX_CHECK_RATE_ATTR_NAME = 'dn'
SM_BACKUP_ENABLE_ATTR_NAME = 'de'
SM_BACKUP_IP_ATTR_NAME = 'io'
SM_AUTO_REBOOT_ATTR_NAME = 'df'
SM_REBOOT_DELAY_ATTR_NAME = 'dp'
SM_LAN_RX_CHECK_ATTR_NAME = 'dq'
SM_LAN_TX_CHECK_ATTR_NAME = 'dr'

# Site Setup form
SS_SITE_NAME_ATTR_NAME = 'td'
SS_LAT_DEG_ATTR_NAME = 'du'
SS_LAT_MIN_ATTR_NAME = 'dv'
SS_LON_DEG_ATTR_NAME = 'dx'
SS_LON_MIN_ATTR_NAME = 'dy'
SS_RX1_LO_ATTR_NAME = 'df'
SS_RX_DC_POWER_ATTR_NAME = 'dn'
SS_RX_10M_ATTR_NAME = 'do'
SS_RX1_SPI_ATTR_NAME = 'dp'
SS_RX1_OFFSET_ATTR_NAME = 'dr'
SS_RX2_LO_ATTR_NAME = 'de'
SS_RX2_SPI_ATTR_NAME = 'dm'
SS_RX2_OFFSET_ATTR_NAME = 'dq'
SS_TX_LO_ATTR_NAME = 'dd'
SS_TX_DC_POWER_ATTR_NAME = 'dg'
SS_TX_10M_ATTR_NAME = 'dh'
SS_TX_SPI_ATTR_NAME = 'di'
SS_TX_OFFSET_ATTR_NAME = 'dk'
SS_DVB_SEARCH_ATTR_NAME = 'dt'
SS_NET_ID_ATTR_NAME = 'dc'
SS_RF_ID_ATTR_NAME = 'db'
SS_LAT_SOUTH_ATTR_NAME = 'dw'
SS_LON_WEST_ATTR_NAME = 'dz'
SS_TDMA_SEARCH_ATTR_NAME = 'ds'
SS_FAR_END_CN_ATTR_NAME = 'dl'
SS_FAR_END_CN_SET_ATTR_NAME = 'tb'
SS_SUBMIT_ATTR_NAME = 'tf'

site_setup_mapping = {
    SS_SITE_NAME_ATTR_NAME: 'site_name',
    SS_LAT_DEG_ATTR_NAME: 'lat_deg',
    SS_LAT_MIN_ATTR_NAME: 'lat_min',
    SS_LON_DEG_ATTR_NAME: 'lon_deg',
    SS_LON_MIN_ATTR_NAME: 'lon_min',
    SS_RX1_LO_ATTR_NAME: 'rx1_lo',
    SS_RX_DC_POWER_ATTR_NAME: 'rx_dc_power',
    SS_RX_10M_ATTR_NAME: 'rx_10m',
    SS_RX1_SPI_ATTR_NAME: 'rx1_spi',
    SS_RX1_OFFSET_ATTR_NAME: 'rx1_offset',
    SS_RX2_LO_ATTR_NAME: 'rx2_lo',
    SS_RX2_SPI_ATTR_NAME: 'rx2_spi',
    SS_RX2_OFFSET_ATTR_NAME: 'rx1_offset',
    SS_TX_LO_ATTR_NAME: 'tx_lo',
    SS_TX_DC_POWER_ATTR_NAME: 'tx_dc_power',
    SS_TX_10M_ATTR_NAME: 'tx_10m',
    SS_TX_SPI_ATTR_NAME: ' tx_spi',
    SS_TX_OFFSET_ATTR_NAME: 'tx_offset',
    SS_DVB_SEARCH_ATTR_NAME: 'dvb_search',
    SS_NET_ID_ATTR_NAME: 'net_id',
    SS_RF_ID_ATTR_NAME: 'rf_id',
    SS_LAT_SOUTH_ATTR_NAME: 'lat_south',
    SS_LON_WEST_ATTR_NAME: 'lon_west',
    SS_TDMA_SEARCH_ATTR_NAME: 'tdma_search',
}

# Profiles->Profile#->Basic form
PROFILE_NUMBER_ATTR_NAME = 'da'
PROFILE_VALID_ATTR_NAME = 'db'
PROFILE_AUTORUN_ATTR_NAME = 'dc'
PROFILE_MODE_ATTR_NAME = 'dd'
PROFILE_TIMEOUT_ATTR_NAME = 'de'
PROFILE_TITLE_ATTR_NAME = 'ta'

# Profile->Profile#->Modulator for
PROFILE_TX_ON_ATTR_NAME = 'dd'
PROFILE_TX_LEVEL_INT_ATTR_NAME = 'db'
PROFILE_TX_LEVEL_FLOAT_ATTR_NAME = 'dc'


# Profiles->Profile#->Timing form
SAT_LON_DEG_ATTR_NAME = 'db'
SAT_LON_MIN_ATTR_NAME = 'dc'
SAT_EAST_WEST_ATTR_NAME = 'dd'
TIMING_MODE_ATTR_NAME = 'de'
TIMING_VALUE_ATTR_NAME = 'df'

# Profiles->Profile#->TLC form
TLC_ENABLE_ATTR_NAME = 'dh'
TLC_MAX_LVL_ATTR_NAME = 'di'
TLC_NET_OWN_ATTR_NAME = 'db'
TLC_AVG_MIN_ATTR_NAME = 'dc'
TLC_CN_HUB_INT_ATTR_NAME = 'dd'
TLC_CN_HUB_FLOAT_ATTR_NAME = 'de'
TLC_CN_STN_INT_ATTR_NAME = 'df'
TLC_CN_STN_FLOAT_ATTR_NAME = 'dg'

# Profiles->Profile#->Modulator form
MOD_TX_ON_ATTR_NAME = 'dd'
MOD_TX_LEVEL_INT_ATTR_NAME = 'db'
MOD_TX_LEVEL_FLOAT_ATTR_NAME = 'dc'

# Profiles->Profile#->TDM/SCPC RX form
TDM_TX_FREQ_ATTR_NAME = 'db'
TDM_TX_SR_ATTR_NAME = 'dc'
TDM_TX_MODCOD_ATTR_NAME = 'de'
TDM_TX_PILOTS_ATTR_NAME = 'dg'
TDM_TX_ROLLOFF_ATTR_NAME = 'df'

# Profiles->Profile#->TDM/SCPC RX form
DEM_CHECK_RX_ATTR_NAME = 'de'
DEM_INPUT_GAIN_ATTR_NAME = 'do'
DEM_RX1_ENABLE_ATTR_NAME = 'df'
DEM_RX1_INPUT_ATTR_NAME = 'dj'
DEM_RX1_FREQ_ATTR_NAME = 'db'
DEM_RX1_SR_ATTR_NAME = 'dc'
DEM_RX2_ENABLE_ATTR_NAME = 'dg'
DEM_RX2_INPUT_ATTR_NAME = 'dk'
DEM_RX2_FREQ_ATTR_NAME = 'dh'
DEM_RX2_SR_ATTR_NAME = 'di'
DEM_RX_VOLTAGE_ATTR_NAME = 'dl'

# Profiles->Profile#->TDMA prot form
TDMA_PROT_STN_NUMBER_ATTR_NAME = 'dd'
TDMA_PROT_FRAME_LENGTH_ATTR_NAME = 'db'
TDMA_PROT_SLOT_LENGTH_ATTR_NAME = 'dc'
TDMA_PROT_NO_STN_CHECK_ATTR_NAME = 'dg'
TDMA_PROT_REC_ALL_TRAF_ATTR_NAME = 'dh'

# Profiles->Profile#->TDMA RF form
TDMA_RF_INPUT_ATTR_NAME = 'd3'
TDMA_RF_SR_ATTR_NAME = 'db'
TDMA_RF_MODCOD_ATTR_NAME = 'dc'
TDMA_RF_ROLL_ATTR_NAME = 'd6'
TDMA_RF_ENH_TABLE_ATTR_NAME = 'd7'
TDMA_RF_RX1_ATTR_NAME = 'dv'
TDMA_RF_TX1_ATTR_NAME = 'dL'
TDMA_RF_ENABLE2_ATTR_NAME = 'dg'
TDMA_RF_RX2_ATTR_NAME = 'dw'
TDMA_RF_TX2_ATTR_NAME = 'dM'
TDMA_RF_ENABLE3_ATTR_NAME = 'dh'
TDMA_RF_RX3_ATTR_NAME = 'dx'
TDMA_RF_TX3_ATTR_NAME = 'dN'
TDMA_RF_ENABLE4_ATTR_NAME = 'di'
TDMA_RF_RX4_ATTR_NAME = 'dy'
TDMA_RF_TX4_ATTR_NAME = 'dO'
TDMA_RF_ENABLE5_ATTR_NAME = 'dj'
TDMA_RF_RX5_ATTR_NAME = 'dz'
TDMA_RF_TX5_ATTR_NAME = 'dP'
TDMA_RF_ENABLE6_ATTR_NAME = 'dk'
TDMA_RF_RX6_ATTR_NAME = 'dA'
TDMA_RF_TX6_ATTR_NAME = 'dQ'
TDMA_RF_ENABLE7_ATTR_NAME = 'dl'
TDMA_RF_RX7_ATTR_NAME = 'dB'
TDMA_RF_TX7_ATTR_NAME = 'dR'
TDMA_RF_ENABLE8_ATTR_NAME = 'dm'
TDMA_RF_RX8_ATTR_NAME = 'dC'
TDMA_RF_TX8_ATTR_NAME = 'dS'
TDMA_RF_ENABLE9_ATTR_NAME = 'dn'
TDMA_RF_RX9_ATTR_NAME = 'dD'
TDMA_RF_TX9_ATTR_NAME = 'dT'
TDMA_RF_ENABLE10_ATTR_NAME = 'do'
TDMA_RF_RX10_ATTR_NAME = 'dE'
TDMA_RF_TX10_ATTR_NAME = 'dU'
TDMA_RF_ENABLE11_ATTR_NAME = 'dp'
TDMA_RF_RX11_ATTR_NAME = 'dF'
TDMA_RF_TX11_ATTR_NAME = 'dV'
TDMA_RF_ENABLE12_ATTR_NAME = 'dq'
TDMA_RF_RX12_ATTR_NAME = 'dG'
TDMA_RF_TX12_ATTR_NAME = 'dW'
TDMA_RF_ENABLE13_ATTR_NAME = 'dr'
TDMA_RF_RX13_ATTR_NAME = 'dH'
TDMA_RF_TX13_ATTR_NAME = 'dX'
TDMA_RF_ENABLE14_ATTR_NAME = 'ds'
TDMA_RF_RX14_ATTR_NAME = 'dI'
TDMA_RF_TX14_ATTR_NAME = 'dY'
TDMA_RF_ENABLE15_ATTR_NAME = 'dt'
TDMA_RF_RX15_ATTR_NAME = 'dJ'
TDMA_RF_TX15_ATTR_NAME = 'd0'
TDMA_RF_ENABLE16_ATTR_NAME = 'du'
TDMA_RF_RX16_ATTR_NAME = 'dK'
TDMA_RF_TX16_ATTR_NAME = 'd1'

# Profiles->Profile#->TDMA BW form
TDMA_BW_ACT_ON_TRAF_ATTR_NAME = 'dx'
TDMA_BW_MIR_LIMIT_ATTR_NAME = 'dy'
TDMA_BW_OPT_LATENCY_ATTR_NAME = 'dv'
TDMA_BW_RT_TO_CIR_ATTR_NAME = 'dw'
TDMA_BW_RQ_SCALE_ATTR_NAME = 'dz'
TDMA_BW_RQ_ACT1_ATTR_NAME = 'db'
TDMA_BW_RQ_ACT2_ATTR_NAME = 'df'
TDMA_BW_RQ_ACT3_ATTR_NAME = 'dj'
TDMA_BW_RQ_ACT4_ATTR_NAME = 'dn'
TDMA_BW_RQ_IDL1_ATTR_NAME = 'dc'
TDMA_BW_RQ_IDL2_ATTR_NAME = 'dg'
TDMA_BW_RQ_IDL3_ATTR_NAME = 'dk'
TDMA_BW_RQ_IDL4_ATTR_NAME = 'do'
TDMA_BW_RQ_DWN1_ATTR_NAME = 'dd'
TDMA_BW_RQ_DWN2_ATTR_NAME = 'dh'
TDMA_BW_RQ_DWN3_ATTR_NAME = 'dl'
TDMA_BW_RQ_DWN4_ATTR_NAME = 'dp'
TDMA_BW_RQ_TOUT1_ATTR_NAME = 'de'
TDMA_BW_RQ_TOUT2_ATTR_NAME = 'di'
TDMA_BW_RQ_TOUT3_ATTR_NAME = 'dm'
TDMA_BW_RQ_TOUT4_ATTR_NAME = 'dq'

# Profiles->Profile#->TDM ACM form
TDM_ACM_ENABLE_ATTR_NAME = 'db'
TDM_ACM_MAX_MODCOD_ATTR_NAME = 'dg'
TDM_ACM_MODCOD2_ATTR_NAME = 'dg'
TDM_ACM_MODCOD3_ATTR_NAME = 'dh'
TDM_ACM_MODCOD4_ATTR_NAME = 'di'
TDM_ACM_MODCOD5_ATTR_NAME = 'dl'
TDM_ACM_MODCOD6_ATTR_NAME = 'dm'
TDM_ACM_MODCOD7_ATTR_NAME = 'dn'
TDM_ACM_MODCOD8_ATTR_NAME = 'do'
TDM_ACM_CN_THRESHOLD_INT_ATTR_NAME = 'dj'
TDM_ACM_CN_THRESHOLD_FLOAT_ATTR_NAME = 'dk'

# Profiles->Profile#->Roaming form
ROAMING_ENABLE_ATTR_NAME = 'db'
ROAMING_TIMEOUT_ATTR_NAME = 'dc'

# Advanced->QoS->Real-time form
RT_CODEC_ATTR_NAME = 'da'
RT_THRESHOLD_ATTR_NAME = 'db'
RT_TIMEOUT_ATTR_NAME = 'dc'

# Advanced->Network->Stations->Station# Station edit form
ST_EDIT_NUMBER_ATTR_NAME = 'db'
ST_EDIT_ON_ATTR_NAME = 'dc'
ST_EDIT_SN_ATTR_NAME = 'dn'
ST_EDIT_REDUNDANT_SN_ATTR_NAME = 'dm'
ST_EDIT_SHAPER_ATTR_NAME = 'de'
ST_EDIT_REQ_PR_ATTR_NAME = 'df'
ST_EDIT_TCPA_ATTR_NAME = 'dd'

# Profiles mode codes
NONE = '0'
SCPC_MODEM = '1'
STAR_STATION = '2'
MESH_STATION = '3'
HUBLESS_STATION = '4'
DAMA_STATION = '5'
CROSSPOL_TEST = '6'
STAR_HUB = '9'
MF_HUB = '10'
OUTROUTE = '11'
INROUTE = '12'
MF_INROUTE = '13'
HUBLESS_MASTER = '14'
DAMA_HUB = '15'
DAMA_INROUTE = '16'
CHANNEL_SIMULATOR = '17'
SPECTRUM_ANALYZER = '18'
COMISSIONING_UNIT = '19'

# Advanced->Network->Stations->Station# form
STATION_NUMBER_ATTR_NAME = 'db'
STATION_ON_ATTR_NAME = 'dc'
STATION_SN_ATTR_NAME = 'dn'
STATION_RED_SN_ATTR_NAME = 'dm'
STATION_SHAPER_ATTR_NAME = 'de'
STATION_REQ_PR_ATTR_NAME = 'df'
STATION_TCPA_ATTR_NAME = 'dd'

# Telnet constants
PRESS_SPACE_TO_CONTINUE = 'Press SPACE to continue Q to exit'

# Advanced->Network->COTM/AMIP form
COTM_AMIP_LOCATION_SOURCE_ATTR_NAME = 'da'
COTM_AMIP_TX_CONTROL_ATTR_NAME = 'dh'
COTM_AMIP_REPORT_LOCATION_TO_HUB_ATTR_NAME = 'dn'
COTM_AMIP_ENABLE_ATTR_NAME = 'di'
COTM_AMIP_PEER_IP_ATTR_NAME = 'ik'
COTM_AMIP_TCP_PORT_ATTR_NAME = 'dl'
COTM_AMIP_VLAN_ATTR_NAME = 'dm'
COTM_AMIP_MODE_ATTR_NAME = 'db'
COTM_AMIP_USE_AMIP_ATTR_NAME = 'dc'
COTM_AMIP_ANTENNA_SETUP_TIMEOUT_ATTR_NAME = 'dd'

# Advanced->Policies->Policy#->Rule#
POLICY_RADIO_BUTTON_ATTR_NAME = 'dz'

POLICY_PRIORITY_802_1Q_VALUE = '1'
POLICY_VLAN_VALUE = '2'
POLICY_TOS_VALUE = '3'
POLICY_IP_PRECEDENCE_VALUE = '13'
POLICY_DSCP_VALUE = '4'
POLICY_ICMP_TYPE_VALUE = '12'
POLICY_PROTOCOL_VALUE = '5'
POLICY_SRC_NET_VALUE = '6'
POLICY_DST_NET_VALUE = '7'
POLICY_SRC_TCP_PORT_VALUE = '8'
POLICY_DST_TCP_PORT_VALUE = '9'
POLICY_SRC_UDP_PORT_VALUE = '10'
POLICY_DST_UDP_PORT_VALUE = '11'
POLICY_SET_QUEUE_VALUE = '18'
POLICY_SET_TS_CHANNEL_VALUE = '19'
POLICY_SET_ACM_CHANNEL_VALUE = '23'
POLICY_DROP_IF_STATION_DOWN_VALUE = '25'
POLICY_SET_TOS_VALUE = '27'
POLICY_GOTO_POLICY_VALUE = '29'
POLICY_COMPRESS_GTP_VALUE = '31'
POLICY_COMPRESS_RTP_VALUE = '21'
POLICY_NO_TCPA_VALUE = '20'
POLICY_NO_SCREENING_VALUE = '22'
POLICY_DROP_VALUE = '17'
POLICY_SET_DSCP_VALUE = '28'
POLICY_CALL_POLICY_VALUE = '30'
POLICY_ENCRYPT_VALUE = '26'

POLICY_NOT_ATTR_NAME = 'dw'
POLICY_GOTO_ACTIONS_ATTR_NAME = 'dx'
POLICY_TERMINATE_AFTER_ACTION = 'dy'

POLICY_PRIORITY_802_1Q_ATTR_NAME = 'dv'
POLICY_VLAN_MIN_ATTR_NAME = 'dc'
POLICY_VLAN_MAX_ATTR_NAME = 'dd'
POLICY_TOS_MIN_ATTR_NAME = 'de'
POLICY_TOS_MAX_ATTR_NAME = 'df'
POLICY_IP_PRECEDENCE_MIN_ATTR_NAME = 'dL'
POLICY_IP_PRECEDENCE_MAX_ATTR_NAME = 'dM'
POLICY_DSCP_MIN_ATTR_NAME = 'dh'
POLICY_DSCP_MAX_ATTR_NAME = 'di'
POLICY_ICMP_TYPE_ATTR_NAME = 'dr'
POLICY_PROTOCOL_ATTR_NAME = 'dg'
POLICY_SRC_NET_IP_ATTR_NAME = 'ij'
POLICY_SRC_NET_MASK_ATTR_NAME = 'mk'
POLICY_DST_NET_IP_ATTR_NAME = 'in'
POLICY_DST_NET_MASK_ATTR_NAME = 'mo'
POLICY_SRC_TCP_PORT_MIN_ATTR_NAME = 'dl'
POLICY_SRC_TCP_PORT_MAX_ATTR_NAME = 'dm'
POLICY_DST_TCP_PORT_MIN_ATTR_NAME = 'dp'
POLICY_DST_TCP_PORT_MAX_ATTR_NAME = 'dq'
POLICY_SRC_UDP_PORT_MIN_ATTR_NAME = 'dA'
POLICY_SRC_UDP_PORT_MAX_ATTR_NAME = 'dB'
POLICY_DST_UDP_PORT_MIN_ATTR_NAME = 'dC'
POLICY_DST_UDP_PORT_MAX_ATTR_NAME = 'dD'

POLICY_SET_QUEUE_SELECTOR_ATTR_NAME = 'ds'
POLICY_SET_TS_CHANNEL_SELECTOR_ATTR_NAME = 'du'
POLICY_SET_ACM_CHANNEL_SELECTOR_ATTR_NAME = 'dE'
POLICY_SET_TOS_ATTR_NAME = 'dH'
POLICY_GOTO_POLICY_ATTR_NAME = 'dJ'
POLICY_SET_DSCP_ATTR_NAME = 'dI'
POLICY_CALL_POLICY_ATTR_NAME = 'dK'
POLICY_ENCRYPT_ATTR_NAME = 'dG'

policy_mapping = {
    POLICY_PRIORITY_802_1Q_VALUE: CheckTypesStr.PRIORITY_802_1Q,
    POLICY_VLAN_VALUE: CheckTypesStr.VLAN,
    POLICY_TOS_VALUE: CheckTypesStr.TOS,
    POLICY_IP_PRECEDENCE_VALUE: 'ip_precedence',
    POLICY_DSCP_VALUE: CheckTypesStr.DSCP,
    POLICY_ICMP_TYPE_VALUE: CheckTypesStr.ICMP_TYPE,
    POLICY_PROTOCOL_VALUE: CheckTypesStr.PROTOCOL,
    POLICY_SRC_NET_VALUE: CheckTypesStr.SRC_NET,
    POLICY_DST_NET_VALUE: CheckTypesStr.DST_NET,
    POLICY_SRC_TCP_PORT_VALUE: CheckTypesStr.SRC_TCP_PORT,
    POLICY_DST_TCP_PORT_VALUE: CheckTypesStr.DST_TCP_PORT,
    POLICY_SRC_UDP_PORT_VALUE: CheckTypesStr.SRC_UDP_PORT,
    POLICY_DST_UDP_PORT_VALUE: CheckTypesStr.DST_UDP_PORT,
    POLICY_SET_QUEUE_VALUE: ActionTypesStr.SET_QUEUE,
    POLICY_SET_TS_CHANNEL_VALUE: ActionTypesStr.SET_TS_CH,
    POLICY_SET_ACM_CHANNEL_VALUE: ActionTypesStr.SET_ACM_CHANNEL,
    POLICY_DROP_IF_STATION_DOWN_VALUE: ActionTypesStr.DROP_IF_STATION_DOWN,
    POLICY_SET_TOS_VALUE: ActionTypesStr.SET_TOS,
    POLICY_GOTO_POLICY_VALUE: ActionTypesStr.GOTO_POLICY,
    POLICY_COMPRESS_GTP_VALUE: ActionTypesStr.COMPRESS_GTP,
    POLICY_COMPRESS_RTP_VALUE: ActionTypesStr.COMPRESS_RTP,
    POLICY_NO_TCPA_VALUE: ActionTypesStr.NO_TCPA,
    POLICY_NO_SCREENING_VALUE: ActionTypesStr.NO_SCREENING,
    POLICY_DROP_VALUE: ActionTypesStr.DROP,
    POLICY_SET_DSCP_VALUE: ActionTypesStr.SET_DSCP,
    POLICY_CALL_POLICY_VALUE: ActionTypesStr.CALL_POLICY,
    POLICY_ENCRYPT_VALUE: ActionTypesStr.ENCRYPT,
}

queues_mapping = {
    'P1(Low)': 'Low',
    'P4(Med)': 'Medium',
    'P5(High)': 'High',
}

# Profiles->Profile#->CrossPol RF form
CROSSPOL_TX_FRQ_ATTR_NAME = 'db'
CROSSPOL_DURATION_ATTR_NAME = 'dc'

# Advanced->IP routing->Static->RIP form
RIP_HUB_VLAN_ATTR_NAME = 'dd'
RIP_STN_VLAN_ATTR_NAME = 'dc'
RIP_NEXT_HOP_ATTR_NAME = 'ib'
RIP_LAN_RX_ATTR_NAME = 'de'
RIP_LAN_DEFAULT_ATTR_NAME = 'df'
RIP_SAT_RX_ATTR_NAME = 'dg'
RIP_SAT_DEFAULT_ATTR_NAME = 'dh'
RIP_ANNOUNCE_ATTR_NAME = 'di'
RIP_PRIORITY_ATTR_NAME = 'dm'
RIP_POLICY_ATTR_NAME = 'dn'
RIP_SHAPER_ATTR_NAME = 'do'

# Profiles->Profile#->Return Channel form
RET_CH_STN_NUM_ATTR_NAME = 'df'
RET_CH_SER_ATTR_NAME = 'dg'
RET_CH_RED_SER_ATTR_NAME = 'dl'
RET_CH_TCPA_ATTR_NAME = 'do'
RET_CH_FRQ_ATTR_NAME = 'db'
RET_CH_SR_ATTR_NAME = 'dc'
RET_CH_MODCOD_ATTR_NAME = 'de'
RET_CH_PILOTS_ATTR_NAME = 'dn'
RET_CH_ROLLOFF_ATTR_NAME = 'dm'
RET_CH_TX_LVL_INT_ATTR_NAME = 'di'
RET_CH_TX_LVL_FLOAT_ATTR_NAME = 'dj'
RET_CH_TX_MODE_ATTR_NAME = 'dk'
RET_CH_CN_HUB_INT_ATTR_NAME = 'dp'
RET_CH_CN_HUB_FLOAT_ATTR_NAME = 'dq'

# Maintenance->Traffic Generator
TR_GEN_ENABLED_ATTR_NAME = 'db'
TR_GEN_MODE_ATTR_NAME = 'di'
TR_GEN_IPV4_ATTR_NAME = 'ic'
TR_GEN_IPV6_ATTR_NAME = 'Ij'
TR_GEN_VLAN_ATTR_NAME = 'df'
TR_GEN_PPS_FROM_ATTR_NAME = 'dd'
TR_GEN_PPS_TO_ATTR_NAME = 'dg'
TR_GEN_PKT_LEN_FROM_ATTR_NAME = 'de'
TR_GEN_PKT_LEN_TO_ATTR_NAME = 'dh'

# Profiles->Profile#->TDMA ACM form
TDMA_ACM_ENABLE_ATTR_NAME = 'db'
TDMA_ACM_MODE_ATTR_NAME = 'dc'
TDMA_MESH_MODCOD_ATTR_NAME = 'dd'
TDMA_RECEIVE_MESH_ATTR_NAME = 'de'
TDMA_ACM_ACTIVE_BPSK_1_2_ATTR_NAME = 'df'
TDMA_ACM_ACTIVE_BPSK_2_3_ATTR_NAME = 'dg'
TDMA_ACM_ACTIVE_BPSK_3_4_ATTR_NAME = 'dh'
TDMA_ACM_ACTIVE_BPSK_5_6_ATTR_NAME = 'di'
TDMA_ACM_ACTIVE_QPSK_1_2_ATTR_NAME = 'dj'
TDMA_ACM_ACTIVE_QPSK_2_3_ATTR_NAME = 'dk'
TDMA_ACM_ACTIVE_QPSK_3_4_ATTR_NAME = 'dl'
TDMA_ACM_ACTIVE_QPSK_5_6_ATTR_NAME = 'dm'
TDMA_ACM_ACTIVE_8PSK_1_2_ATTR_NAME = 'dn'
TDMA_ACM_ACTIVE_8PSK_2_3_ATTR_NAME = 'do'
TDMA_ACM_ACTIVE_8PSK_3_4_ATTR_NAME = 'dp'
TDMA_ACM_ACTIVE_8PSK_5_6_ATTR_NAME = 'dq'
TDMA_ACM_ACTIVE_16APSK_1_2_ATTR_NAME = 'dr'
TDMA_ACM_ACTIVE_16APSK_2_3_ATTR_NAME = 'ds'
TDMA_ACM_ACTIVE_16APSK_3_4_ATTR_NAME = 'dt'
TDMA_ACM_ACTIVE_16APSK_5_6_ATTR_NAME = 'du'

TDMA_ACM_THRESH_BPSK_1_2_ATTR_NAME = 'ta'
TDMA_ACM_THRESH_BPSK_2_3_ATTR_NAME = 'tb'
TDMA_ACM_THRESH_BPSK_3_4_ATTR_NAME = 'tc'
TDMA_ACM_THRESH_BPSK_5_6_ATTR_NAME = 'td'
TDMA_ACM_THRESH_QPSK_1_2_ATTR_NAME = 'te'
TDMA_ACM_THRESH_QPSK_2_3_ATTR_NAME = 'tf'
TDMA_ACM_THRESH_QPSK_3_4_ATTR_NAME = 'tg'
TDMA_ACM_THRESH_QPSK_5_6_ATTR_NAME = 'th'
TDMA_ACM_THRESH_8PSK_1_2_ATTR_NAME = 'ti'
TDMA_ACM_THRESH_8PSK_2_3_ATTR_NAME = 'tj'
TDMA_ACM_THRESH_8PSK_3_4_ATTR_NAME = 'tk'
TDMA_ACM_THRESH_8PSK_5_6_ATTR_NAME = 'tl'
TDMA_ACM_THRESH_16APSK_1_2_ATTR_NAME = 'tm'
TDMA_ACM_THRESH_16APSK_2_3_ATTR_NAME = 'tn'
TDMA_ACM_THRESH_16APSK_3_4_ATTR_NAME = 'to'
TDMA_ACM_THRESH_16APSK_5_6_ATTR_NAME = 'tp'

# Maintenance -> Network script
NET_SCRIPT_TYPE_ATTR_NAME = 'db'
NET_SCRIPT_SN_VALUE_ATTR_NAME = 'dc'
NET_SCRIPT_COMMAND_ATTR_NAME = 'aa'

# Advanced -> Shapers -> Shaper Channel#
SHAPER_TEMPLATE_ATTR_NAME = 'dv'
SHAPER_UPPER_ENABLE_ATTR_NAME = 'dc'
SHAPER_MAX_ENABLE_ATTR_NAME = 'df'
SHAPER_MIN_ENABLE_ATTR_NAME = 'dj'
SHAPER_WFQ_ENABLE_ATTR_NAME = 'dn'
SHAPER_NIGHT_ENABLE_ATTR_NAME = 'dr'
SHAPER_CIR_ATTR_NAME = 'db'
SHAPER_NAME_ATTR_NAME = 'tb'
SHAPER_UPPER_CHANNEL_ATTR_NAME = 'dd'
SHAPER_UP_QUEUE_ATTR_NAME = 'de'
SHAPER_MAX_CIR_ATTR_NAME = 'dg'
SHAPER_MAX_SLOPE_ATTR_NAME = 'dh'
SHAPER_MIN_CIR_ATTR_NAME = 'dk'
SHAPER_DOWN_SLOPE_ATTR_NAME = 'dl'
SHAPER_UP_SLOPE_ATTR_NAME = 'dm'
SHAPER_WFQ1_ATTR_NAME = 'do'
SHAPER_WFQ2_ATTR_NAME = 'dx'
SHAPER_WFQ3_ATTR_NAME = 'dy'
SHAPER_WFQ4_ATTR_NAME = 'dz'
SHAPER_WFQ5_ATTR_NAME = 'dA'
SHAPER_WFQ6_ATTR_NAME = 'dB'
SHAPER_NIGHT_CIR_ATTR_NAME = 'ds'
SHAPER_NIGHT_START_ATTR_NAME = 'dt'
SHAPER_NIGHT_END_ATTR_NAME = 'du'

shaper_mapping = {
    SHAPER_TEMPLATE_ATTR_NAME: 'template',
    SHAPER_UPPER_ENABLE_ATTR_NAME: 'upper_enable',
    SHAPER_MAX_ENABLE_ATTR_NAME: 'max_enable',
    SHAPER_MIN_ENABLE_ATTR_NAME: 'min_enable',
    SHAPER_WFQ_ENABLE_ATTR_NAME: 'wfq_enable',
    SHAPER_NIGHT_ENABLE_ATTR_NAME: 'night_enable',
    SHAPER_CIR_ATTR_NAME: 'cir',
    SHAPER_NAME_ATTR_NAME: 'name',
    SHAPER_UPPER_CHANNEL_ATTR_NAME: 'upper_channel',
    SHAPER_UP_QUEUE_ATTR_NAME: 'up_queue',
    SHAPER_MAX_CIR_ATTR_NAME: 'max_cir',
    SHAPER_MAX_SLOPE_ATTR_NAME: 'max_slope',
    SHAPER_MIN_CIR_ATTR_NAME: 'min_cir',
    SHAPER_DOWN_SLOPE_ATTR_NAME: 'down_slope',
    SHAPER_UP_SLOPE_ATTR_NAME: 'up_slope',
    SHAPER_WFQ1_ATTR_NAME: 'wfq1',
    SHAPER_WFQ2_ATTR_NAME: 'wfq2',
    SHAPER_WFQ3_ATTR_NAME: 'wfq3',
    SHAPER_WFQ4_ATTR_NAME: 'wfq4',
    SHAPER_WFQ5_ATTR_NAME: 'wfq5',
    SHAPER_WFQ6_ATTR_NAME: 'wfq6',
    SHAPER_NIGHT_CIR_ATTR_NAME: 'night_cir',
    SHAPER_NIGHT_START_ATTR_NAME: 'night_start',
    SHAPER_NIGHT_END_ATTR_NAME: 'night_end',
}
shaper_queue_mapping = {  # mapping UHP queueing to NMS up_queue naming convention
    'P1(Low)': ShaperUpQueueStr.Q1,
    'P2': ShaperUpQueueStr.Q2,
    'P3': ShaperUpQueueStr.Q3,
    'P4(Med)': ShaperUpQueueStr.Q4,
    'P5': ShaperUpQueueStr.Q5,
    'P6': ShaperUpQueueStr.Q6,
    'P7(High)': ShaperUpQueueStr.Q7,
    'Q->Q': ShaperUpQueueStr.Q_TO_Q,
}

SCPC_TLC_RED_VLAN_ATTR_NAME = 'di'
SCPC_TLC_RED_PASSWORD_ATTR_NAME = 'tb'
SCPC_TLC_RED_SCPC_TLC_EN_ATTR_NAME = 'dg'
SCPC_TLC_RED_TLC_PEER_IP_ATTR_NAME = 'ih'
SCPC_TLC_RED_MONITORING_ATTR_NAME = 'da'
SCPC_TLC_RED_CONTROL_ATTR_NAME = 'db'
SCPC_TLC_RED_ALLOW_LOCAL_ATTR_NAME = 'dl'
SCPC_TLC_RED_RED_ENABLE_ATTR_NAME = 'dd'
SCPC_TLC_RED_REMOTE_IP_ATTR_NAME = 'if'
SCPC_TLC_RED_LOCAL_IP_ATTR_NAME = 'ie'
SCPC_TLC_RED_FAULT_TIMEOUT_ATTR_NAME = 'dk'
SCPC_TLC_RED_LINK_TIMEOUT_ATTR_NAME = 'dj'
SCPC_TLC_RED_SER_MON_ATTR_NAME = 'dm'
scpc_tlc_red_mapping = {
    SCPC_TLC_RED_VLAN_ATTR_NAME: 'vlan',
    SCPC_TLC_RED_PASSWORD_ATTR_NAME: 'password',
    SCPC_TLC_RED_SCPC_TLC_EN_ATTR_NAME: 'scpc_tlc_enable',
    SCPC_TLC_RED_TLC_PEER_IP_ATTR_NAME: 'scpc_tlc_peer_ip',
    SCPC_TLC_RED_MONITORING_ATTR_NAME: 'monitoring',
    SCPC_TLC_RED_CONTROL_ATTR_NAME: 'control',
    SCPC_TLC_RED_ALLOW_LOCAL_ATTR_NAME: 'allow_local_config',
    SCPC_TLC_RED_RED_ENABLE_ATTR_NAME: 'red_enable',
    SCPC_TLC_RED_REMOTE_IP_ATTR_NAME: 'red_remote_ip',
    SCPC_TLC_RED_LOCAL_IP_ATTR_NAME: 'red_local_ip',
    SCPC_TLC_RED_FAULT_TIMEOUT_ATTR_NAME: 'red_fault_timeout',
    SCPC_TLC_RED_LINK_TIMEOUT_ATTR_NAME: 'red_link_timeout',
    SCPC_TLC_RED_SER_MON_ATTR_NAME: 'red_ser_monitor',
}
