from src.custom_logger import LOGGING, WARNING
from src.options_providers.options_provider import CHROME_CONNECT

system = {
    LOGGING: WARNING,
    CHROME_CONNECT: {
        'no_gui': True
    }
}

options = {
    'dbeditor': {
        'access': {
            'rows': 1024,
            'vars': 5,
        },
        'alert': {
            'rows': 2048,
            'vars': 11,
        },
        'bal_controller': {
            'rows': 32,
            'vars': 48,
        },
        'buf_event': {
            'rows': 2097216,
            'vars': 1,
        },
        'camera': {
            'rows': 64,
            'vars': 4,
        },
        'controller': {
            'rows': 512,
            'vars': 538,
        },
        'dashboard': {
            'rows': 256,
            'vars': 196,
        },
        'device': {
            'rows': 2048,
            'vars': 57,
        },
        'event': {
            'rows': 64,
            'vars': 6,
        },
        'group': {
            'rows': 512,
            'vars': 5,
        },
        'locktable': {
            'rows': 128,
            'vars': 1,
        },
        'maxrow': {
            'rows': 256,
            'vars': 1,
        },
        'module': {
            'rows': 16,
            'vars': 17,
        },
        'network': {
            'rows': 128,
            'vars': 106,
        },
        'nms': {
            'rows': 1,
            'vars': 88,
        },
        'policy': {
            'rows': 512,
            'vars': 5,
        },
        'polrule': {
            'rows': 10000,
            'vars': 29,
        },
        'port_map': {
            'rows': 16000,
            'vars': 5,
        },
        'profile_set': {
            'rows': 128,
            'vars': 73,
        },
        'qos': {
            'rows': 1024,
            'vars': 7,
        },
        'rip_router': {
            'rows': 256,
            'vars': 11,
        },
        'route': {
            'rows': 65000,
            'vars': 15,
        },
        'sch_range': {
            'rows': 64,
            'vars': 5,
        },
        'sch_service': {
            'rows': 128,
            'vars': 9,
        },
        'sch_task': {
            'rows': 512,
            'vars': 8,
        },
        'scheduler': {
            'rows': 64,
            'vars': 14,
        },
        'server': {
            'rows': 64,
            'vars': 29,
        },
        'service': {
            'rows': 512,
            'vars': 16,
        },
        'shaper': {
            'rows': 2048,
            'vars': 27,
        },
        'sr_controller': {
            'rows': 32,
            'vars': 61,
        },
        'sr_license': {
            'rows': 256,
            'vars': 22,
        },
        'sr_teleport': {
            'rows': 128,
            'vars': 25,
        },
        'station': {
            'rows': 32768,
            'vars': 252,
        },
        'sw_upload': {
            'rows': 32,
            'vars': 26,
        },
        'teleport': {
            'rows': 128,
            'vars': 24,
        },
        'user': {
            'rows': 512,
            'vars': 9,
        },
        'vno': {
            'rows': 512,
            'vars': 197,
        },
    },
    'search_valid': [
        'network',
    ],
    'search_invalid': [
        'nms',
        True,
        False,
        None,
        'null',
        -1,
        9999999999,
        'a' * 1000,
        ' ',
        '#',
        '?',
        'uhp',
        'НМС',
        'sudo'
    ],
    'fs_dirs': [
        'scripts/',
        'sounds/',
        'logo/',
        'footprints/',
        'core_data/',
        'software/',
        'config/',
        '..'
    ],
    'fs_invalid_dirs': [
        'nms',
        'uhp',
        '~'

    ],
    'invalid_objects': [
        '211131',
        ' ',
        '$%',
        'ывсаыа',
        'spring',
        '?'
    ],
    'invalid_numbers': [
        '-1',
        'addadada',
        ' ',
        '999999999',
        'тунц'
    ],
    'invalid_vars': [
        'dadaad',
        'фываооаы',
        '          ',
        '!!!!!!!!!!!!!!!!!!!!!'
    ],
    'valid_dashboard_objects': [
        'bal_controller',
        'controller',
        'dashboard',
        'device',
        'network',
        'nms',
        'server',
        'sr_controller',
        'sr_teleport',
        'station',
        'sw_upload',
        'vno',
    ],
    'invalid_dashboard_objects': [
        'access',
        'alert',
        'camera',
        'group',
        'policy',
        'polrule',
        'port_map',
        'profile_set',
        'rip_router',
        'route',
        'sch_range',
        'sch_service',
        'sch_task',
        'scheduler',
        'service',
        'shaper',
        'teleport',
        'user',
    ],
    'valid_graph_objects': [
        'controller',
        'network',
        'station',
        'vno',
    ],
    'invalid_graph_objects': [
        'access',
        'alert',
        'bal_controller',
        'camera',
        'dashboard',
        'device',
        'nms',
        'group',
        'policy',
        'polrule',
        'port_map',
        'profile_set',
        'rip_router',
        'route',
        'sch_range',
        'sch_service',
        'sch_task',
        'scheduler',
        'server',
        'service',
        'shaper',
        'sr_controller',
        'sr_teleport',
        'sw_upload',
        'teleport',
        'user',
    ],
    'test_shown_logs_iterations': 97,
    'station_tool_vars_frontend': [  # according to frontend
        'name',
        'state',
        'faults',
        'serial',
        'red_serial',
        'enable',
        'mode',
        'rx_controller',
        'rx_ctr_act',
        'rx_number',
        'sw_load_id',
        'ext_gateway',
        'profile_set',
        'sw_version',
        'rx_errors',
        'cn_on_hub',
        'station_cn',
        'station_2_cn',
        'station_tx',
        'tx_margin',
        'forward_modcod',
        'return_modcod',
        'gateway_modcod',
        'return_rate_all',
        'forward_rate_all',
        'tx2_speed_all',
        'return_rate1',
        'return_rate2',
        'return_rate3',
        'return_rate4',
        'return_rate5',
        'return_rate6',
        'return_rate7',
        'forward_rate1',
        'forward_rate2',
        'forward_rate3',
        'forward_rate4',
        'forward_rate5',
        'forward_rate6',
        'forward_rate7',
        'bw_rq',
        'cur_lat_deg',
        'cur_lat_min',
        'cur_lon_deg',
        'cur_lon_min',
        'hub_up_shaper',
        'stn_up_shaper',
        'last_fault',
        'last_no_fault',
        'fault_times',
        'last_up',
        'last_down',
        'down_times',
        'clear_time',
    ],
    'station_tool_vars': [
        'name',
        'routes',
        'rip_routers',
        'port_maps',
        'sch_tasks',
        'enable',
        'serial',
        'mode',
        'rx_controller',
        'icon',
        'alert_mode',
        'traffic_scale',
        'level_scale',
        'force_config',
        'customer',
        'phone1',
        'phone2',
        'address',
        'email',
        'comment',
        'red_serial',
        'roaming',
        'ext_gateway',
        'no_balancing',
        'profile_set',
        'scheduler',
        'sw_load_id',
        'rx_ctr_dyn',
        'rx_ctr_act',
        'rx_next',
        'tx_number',
        'rx_number',
        'fixed_location',
        'cur_lat_deg',
        'cur_lat_min',
        'cur_lon_deg',
        'cur_lon_min',
        'time_zone',
        'hub_up_shaper',
        'stn_up_shaper',
        'rq_profile',
        'rt_codec',
        'rt_threshold',
        'rt_timeout',
        'hub_low_cn',
        'hub_high_cn',
        'station_low_cn',
        'station_high_cn',
        'ip_screening',
        'dns_caching',
        'arp_timeout',
        'proxy_arp',
        'tftp_server',
        'tftp_vlan',
        'mcast_mode',
        'sntp_mode',
        'ctl_protect',
        'x509_mode',
        'snmp_mode',
        'dhcp_mode',
        'nat_enable',
        'rip_mode',
        'tcpa_enable',
        'sm_enable',
        'mod_queue1',
        'mod_queue2',
        'mod_queue3',
        'mod_queue4',
        'mod_queue5',
        'mod_queue6',
        'mod_queue7',
        'mod_que_ctl',
        'state',
        'num_state',
        'current_ip',
        'nms_version',
        'config_csum',
        'forward_rate_all',
        'tx2_speed_all',
        'return_rate_all',
        'forward_rate1',
        'forward_rate2',
        'forward_rate3',
        'forward_rate4',
        'forward_rate5',
        'forward_rate6',
        'forward_rate7',
        'return_rate1',
        'return_rate2',
        'return_rate3',
        'return_rate4',
        'return_rate5',
        'return_rate6',
        'return_rate7',
        'tx_errors',
        'rx_errors',
        'station_cn',
        'station_2_cn',
        'station_tx',
        'cn_on_hub',
        'sc_stn_cn',
        'sc_hub_cn',
        'forward_acm',
        'gateway_acm',
        'forward_modcod',
        'gateway_modcod',
        'return_acm',
        'return_modcod',
        'bw_rq',
        'dama_mc',
        'tx_margin',
        'sw_version',
        'faults',
        'clear_time',
        'last_up',
        'last_down',
        'down_times',
        'down_dur',
        'last_fault',
        'last_no_fault',
        'fault_times',
        'fault_dur',
        'last_reply',
        'last_lost',
        'lost_times',
        # 'lost_dur',
        # 'forward_load',
        # 'return_load',
        # 'hub_up_shaper',
        # 'stn_up_shaper',
    ],
    'dir_names': ['scripts', 'sounds', 'logo', 'footprints', 'core_data', 'software', 'config'],

    'max_file_size_mb': 15.5,

    'map_marker_modes': [
        'num_state',
        'cn_on_hub',
        'sc_hub_cn',
        'station_cn',
        'sc_station_cn',
        'forward_acm',
        'station_acm',
    ],
    'search_tool_unique_names': {
        'nms': 'reliable_nms',
        'server': 'amazing_server',
        'group': 'prominent_group',
        'user': 'renowned_user',
        'alert': 'shiny_alert',
        'dashboard': 'intelligent_dashboard',
        'network': 'brilliant_network',
        'teleport': 'beautiful_teleport',
        'controller': 'fashionable_controller',
        'vno': 'charming_vno',
        'service': 'elegant_service',
        'shaper': 'trustworthy_shaper',
        'policy': 'ambitious_policy',
        'sr_controller': 'lovely_sr_controller',
        'sr_teleport': 'agreeable_sr_teleport',
        'device': 'courteous_device',
        'sr_license': 'helpful_sr_license',
        'bal_controller': 'witty_bal_controller',
        'profile_set': 'gorgeous_profile_set',
        'sw_upload': 'supportive_sw_upload',
        'camera': 'faithful_camera',
        'scheduler': 'passionate_scheduler',
        'sch_range': 'sincere_sch_range',
        'sch_service': 'adorable_sch_service',
        'station': 'enthusiastic_station',
        'sch_task': 'seductive_sch_task',
        'qos': 'intelligent_qos',
    }
}
