from src.enum_types_constants import ControllerModes, ModcodModes, TdmaInputModes, RollofModes, TdmaModcod, \
    CheckboxStr

options = {
    'stations_tx_lvl': '36',
    'network': {
        'name': 'test_net',
        'dev_password': 'teste',
    },
    'teleport1': {
        'name': 'test_tp1',
        'tx_lo': '0',
        'rx1_lo': '0',
        'rx2_lo': '0',
        'sat_name': 'test_sat1'
    },
    'mf_hub': {
        'name': f'test_ctrl',
        'mode': ControllerModes.MF_HUB,
        'teleport': f'teleport:0',
        'net_ID': '132',
        'uhp_model': '2',  # model UHP-200
        'tx_frq': '960000',
        'tx_sr': '1500',
        'tx_modcod': ModcodModes.SF_QPSK_3_4,
        'tx_level': '40',
        'rx1_frq': '960000',
        'rx1_sr': '1500',
        'tdma_input': TdmaInputModes.RX1,
        'tdma_sr': 500,
        'tdma_roll': RollofModes.R20,
        'mf1_rx': 1000000,
        'mf1_tx': 1000000,
        'tdma_mc': TdmaModcod._QPSK_2_3,
        'tdma_acm': '1',
        'no_stn_check': '1',
        'tx_on': '1',
    },
    'inroute1': {
        'name': f'test_ctrl_Inr1',
        'inroute': '2',
        'mode': ControllerModes.INROUTE,
        'tx_controller': 'controller: 0',
        'teleport': f'teleport:0',
        'uhp_model': '2',  # model UHP-200
        'stn_number': 6,
        'frame_length': 128,
        'slot_length': 10,
        'tdma_input': TdmaInputModes.RX1,
        'tdma_sr': 1000,
        'tdma_roll': RollofModes.R20,
        'mf1_rx': 1002000,
        'mf1_tx': 1002000,
        'tdma_mc': TdmaModcod._8PSK_2_3,
        'tdma_acm': '1',
        'no_stn_check': '1',
    },
    'inroute2': {
        'name': f'test_ctrl_Inr2',
        'inroute': '3',
        'mode': ControllerModes.INROUTE,
        'tx_controller': 'controller: 0',
        'teleport': f'teleport:0',
        'uhp_model': '2',  # model UHP-200
        'stn_number': 6,
        'frame_length': 128,
        'slot_length': 10,
        'tdma_input': TdmaInputModes.RX1,
        'tdma_sr': 2000,
        'tdma_roll': RollofModes.R20,
        'mf1_rx': 1006000,
        'mf1_tx': 1006000,
        'tdma_mc': TdmaModcod._16APSK_2_3,
        'tdma_acm': '1',
        'no_stn_check': '1',
    },
    'inroute3': {
        'name': f'test_ctrl_Inr3',
        'inroute': '4',
        'mode': ControllerModes.INROUTE,
        'tx_controller': 'controller: 0',
        'teleport': f'teleport:0',
        'uhp_model': '2',  # model UHP-200
        'stn_number': 6,
        'frame_length': 128,
        'slot_length': 10,
        'tdma_input': TdmaInputModes.RX1,
        'tdma_sr': 1500,
        'tdma_roll': RollofModes.R20,
        'mf1_rx': 1009000,
        'mf1_tx': 1009000,
        'tdma_mc': TdmaModcod._QPSK_3_4,
        'tdma_acm': '1',
        'no_stn_check': '1',
    },
    'service': {
        'name': 'test_service'
    },
    'service_ping': {
        'name': 'ping_service',
        'hub_vlan': 206,
        'stn_vlan': 306,
        'stn_normal': CheckboxStr.ON,
    }
}
