# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
# Edited for UHP support
#   smidump -f python RFC1213-MIB

MIB = {
    "moduleName": "RFC1213-MIB",

    "RFC1213-MIB": {
        "nodetype": "module",
        "language": "SMIv1",
    },

    "imports": (
        {"module": "RFC1155-SMI", "name": "mgmt"},
        {"module": "RFC1155-SMI", "name": "NetworkAddress"},
        {"module": "RFC1155-SMI", "name": "IpAddress"},
        {"module": "RFC1155-SMI", "name": "Counter"},
        {"module": "RFC1155-SMI", "name": "Gauge"},
        {"module": "RFC1155-SMI", "name": "TimeTicks"},
        {"module": "", "name": "OBJECT-TYPE"},
    ),

    "typedefs": {
        "DisplayString": {
            "basetype": "OctetString",
        },
        "PhysAddress": {
            "basetype": "OctetString",
        },
    },  # typedefs

    "nodes": {
        "mib2": {
            "nodetype": "node",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1",
        },  # node
        "system": {
            "nodetype": "node",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.1",
        },  # node
        "sysDescr": {
            "nodetype": "scalar",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.1.1",
            "status": "current",
            "syntax": {
                "type": {
                    "basetype": "OctetString",
                    "parent module": {
                        "name": "RFC1213-MIB",
                        "type": "DisplayString",
                    },
                    "ranges": [
                        {
                            "min": "0",
                            "max": "255"
                        },
                    ],
                    "range": {
                        "min": "0",
                        "max": "255"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A textual description of the entity.  This value
should include the full name and version
identification of the system's hardware type,
software operating-system, and networking
software.  It is mandatory that this only contain
printable ASCII characters.""",
        },  # scalar
        "sysObjectId": {
            "nodetype": "scalar",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.1.2",
            "status": "current",
            "syntax": {
                "type": {"module": "", "name": "ObjectIdentifier"},
            },
            "access": "readonly",
            "description":
                """The vendor's authoritative identification of the
network management subsystem contained in the
entity.  This value is allocated within the SMI
enterprises subtree (1.3.6.1.4.1) and provides an
easy and unambiguous means for determining `what
kind of box' is being managed.  For example, if
vendor `Flintstones, Inc.' was assigned the
subtree 1.3.6.1.4.1.4242, it could assign the
identifier 1.3.6.1.4.1.4242.1.1 to its `Fred
Router'.""",
        },  # scalar
        "sysUpTime": {
            "nodetype": "scalar",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.1.3",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-SMI", "name": "TimeTicks"},
            },
            "access": "readonly",
            "description":
                """The time (in hundredths of a second) since the
network management portion of the system was last
re-initialized.""",
        },  # scalar
        "sysContact": {
            "nodetype": "scalar",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.1.4",
            "status": "current",
            "syntax": {
                "type": {
                    "basetype": "OctetString",
                    "parent module": {
                        "name": "RFC1213-MIB",
                        "type": "DisplayString",
                    },
                    "ranges": [
                        {
                            "min": "0",
                            "max": "255"
                        },
                    ],
                    "range": {
                        "min": "0",
                        "max": "255"
                    },
                },
            },
            "access": "readwrite",
            "description":
                """The textual identification of the contact person
for this managed node, together with information
on how to contact this person.""",
        },  # scalar
        "sysName": {
            "nodetype": "scalar",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.1.5",
            "status": "current",
            "syntax": {
                "type": {
                    "basetype": "OctetString",
                    "parent module": {
                        "name": "RFC1213-MIB",
                        "type": "DisplayString",
                    },
                    "ranges": [
                        {
                            "min": "0",
                            "max": "255"
                        },
                    ],
                    "range": {
                        "min": "0",
                        "max": "255"
                    },
                },
            },
            "access": "readwrite",
            "description":
                """An administratively-assigned name for this
managed node.  By convention, this is the node's
fully-qualified domain name.""",
        },  # scalar
        "sysLocation": {
            "nodetype": "scalar",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.1.6",
            "status": "current",
            "syntax": {
                "type": {
                    "basetype": "OctetString",
                    "parent module": {
                        "name": "RFC1213-MIB",
                        "type": "DisplayString",
                    },
                    "ranges": [
                        {
                            "min": "0",
                            "max": "255"
                        },
                    ],
                    "range": {
                        "min": "0",
                        "max": "255"
                    },
                },
            },
            "access": "readwrite",
            "description":
                """The physical location of this node (e.g.,
`telephone closet, 3rd floor').""",
        },  # scalar
        "sysServices": {
            "nodetype": "scalar",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.1.7",
            "status": "current",
            "syntax": {
                "type": {
                    "basetype": "Integer32",
                    "ranges": [
                        {
                            "min": "0",
                            "max": "127"
                        },
                    ],
                    "range": {
                        "min": "0",
                        "max": "127"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A value which indicates the set of services that
this entity primarily offers.

The value is a sum.  This sum initially takes the
value zero, Then, for each layer, L, in the range
1 through 7, that this node performs transactions
for, 2 raised to (L - 1) is added to the sum.  For
example, a node which performs primarily routing
functions would have a value of 4 (2^(3-1)).  In
contrast, a node which is a host offering
application services would have a value of 72
(2^(4-1) + 2^(7-1)).  Note that in the context of
the Internet suite of protocols, values should be
calculated accordingly:

     layer  functionality
         1  physical (e.g., repeaters)
         2  datalink/subnetwork (e.g., bridges)
         3  internet (e.g., IP gateways)
         4  end-to-end  (e.g., IP hosts)
         7  applications (e.g., mail relays)

For systems including OSI protocols, layers 5 and
6 may also be counted.""",
        },  # scalar
        "sysOrLast": {
            "nodetype": "scalar",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.1.8",
            "status": "current",
            "type": {"module": "", "name": "Integer32"},
            "access": "readonly",
            "description": "",
        },  # scalar
        "interfaces": {
            "nodetype": "node",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2",
        },  # node
        "ifNumber": {
            "nodetype": "scalar",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.1",
            "status": "current",
            "syntax": {
                "type": {"module": "", "name": "Integer32"},
            },
            "access": "readonly",
            "description":
                """The number of network interfaces (regardless of
their current state) present on this system.""",
        },  # scalar
        "ifDescr": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.2",
            "status": "current",
            "syntax": {
                "type": {
                    "basetype": "OctetString",
                    "parent module": {
                        "name": "RFC1213-MIB",
                        "type": "DisplayString",
                    },
                    "ranges": [
                        {
                            "min": "0",
                            "max": "255"
                        },
                    ],
                    "range": {
                        "min": "0",
                        "max": "255"
                    },
                },
            },
            "access": "readonly",
            "description":
                """A textual string containing information about the
interface.  This string should include the name of
the manufacturer, the product name and the version
of the hardware interface.""",
        },  # column
        "ifType": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.3",
            "status": "current",
            "syntax": {
                "type": {
                    "basetype": "Enumeration",
                    "other": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "regular1822": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                    "hdh1822": {
                        "nodetype": "namednumber",
                        "number": "3"
                    },
                    "ddnX25": {
                        "nodetype": "namednumber",
                        "number": "4"
                    },
                    "rfc877x25": {
                        "nodetype": "namednumber",
                        "number": "5"
                    },
                    "ethernetCsmacd": {
                        "nodetype": "namednumber",
                        "number": "6"
                    },
                    "iso88023Csmacd": {
                        "nodetype": "namednumber",
                        "number": "7"
                    },
                    "iso88024TokenBus": {
                        "nodetype": "namednumber",
                        "number": "8"
                    },
                    "iso88025TokenRing": {
                        "nodetype": "namednumber",
                        "number": "9"
                    },
                    "iso88026Man": {
                        "nodetype": "namednumber",
                        "number": "10"
                    },
                    "starLan": {
                        "nodetype": "namednumber",
                        "number": "11"
                    },
                    "proteon10Mbit": {
                        "nodetype": "namednumber",
                        "number": "12"
                    },
                    "proteon80Mbit": {
                        "nodetype": "namednumber",
                        "number": "13"
                    },
                    "hyperchannel": {
                        "nodetype": "namednumber",
                        "number": "14"
                    },
                    "fddi": {
                        "nodetype": "namednumber",
                        "number": "15"
                    },
                    "lapb": {
                        "nodetype": "namednumber",
                        "number": "16"
                    },
                    "sdlc": {
                        "nodetype": "namednumber",
                        "number": "17"
                    },
                    "ds1": {
                        "nodetype": "namednumber",
                        "number": "18"
                    },
                    "e1": {
                        "nodetype": "namednumber",
                        "number": "19"
                    },
                    "basicISDN": {
                        "nodetype": "namednumber",
                        "number": "20"
                    },
                    "primaryISDN": {
                        "nodetype": "namednumber",
                        "number": "21"
                    },
                    "propPointToPointSerial": {
                        "nodetype": "namednumber",
                        "number": "22"
                    },
                    "ppp": {
                        "nodetype": "namednumber",
                        "number": "23"
                    },
                    "softwareLoopback": {
                        "nodetype": "namednumber",
                        "number": "24"
                    },
                    "eon": {
                        "nodetype": "namednumber",
                        "number": "25"
                    },
                    "ethernet3Mbit": {
                        "nodetype": "namednumber",
                        "number": "26"
                    },
                    "nsip": {
                        "nodetype": "namednumber",
                        "number": "27"
                    },
                    "slip": {
                        "nodetype": "namednumber",
                        "number": "28"
                    },
                    "ultra": {
                        "nodetype": "namednumber",
                        "number": "29"
                    },
                    "ds3": {
                        "nodetype": "namednumber",
                        "number": "30"
                    },
                    "sip": {
                        "nodetype": "namednumber",
                        "number": "31"
                    },
                    "frameRelay": {
                        "nodetype": "namednumber",
                        "number": "32"
                    },
                    "rs232": {
                        "nodetype": "namednumber",
                        "number": "33"
                    },
                    "para": {
                        "nodetype": "namednumber",
                        "number": "34"
                    },
                    "arcnet": {
                        "nodetype": "namednumber",
                        "number": "35"
                    },
                    "arcnetPlus": {
                        "nodetype": "namednumber",
                        "number": "36"
                    },
                    "atm": {
                        "nodetype": "namednumber",
                        "number": "37"
                    },
                    "miox25": {
                        "nodetype": "namednumber",
                        "number": "38"
                    },
                    "sonet": {
                        "nodetype": "namednumber",
                        "number": "39"
                    },
                    "x25ple": {
                        "nodetype": "namednumber",
                        "number": "40"
                    },
                    "iso88022llc": {
                        "nodetype": "namednumber",
                        "number": "41"
                    },
                    "localTalk": {
                        "nodetype": "namednumber",
                        "number": "42"
                    },
                    "smdsDxi": {
                        "nodetype": "namednumber",
                        "number": "43"
                    },
                    "frameRelayService": {
                        "nodetype": "namednumber",
                        "number": "44"
                    },
                    "v35": {
                        "nodetype": "namednumber",
                        "number": "45"
                    },
                    "hssi": {
                        "nodetype": "namednumber",
                        "number": "46"
                    },
                    "hippi": {
                        "nodetype": "namednumber",
                        "number": "47"
                    },
                    "modem": {
                        "nodetype": "namednumber",
                        "number": "48"
                    },
                    "aal5": {
                        "nodetype": "namednumber",
                        "number": "49"
                    },
                    "sonetPath": {
                        "nodetype": "namednumber",
                        "number": "50"
                    },
                    "sonetVT": {
                        "nodetype": "namednumber",
                        "number": "51"
                    },
                    "smdsIcip": {
                        "nodetype": "namednumber",
                        "number": "52"
                    },
                    "propVirtual": {
                        "nodetype": "namednumber",
                        "number": "53"
                    },
                    "propMultiplexor": {
                        "nodetype": "namednumber",
                        "number": "54"
                    },
                    "ieee80212": {
                        "nodetype": "namednumber",
                        "number": "55"
                    },
                    "fibreChannel": {
                        "nodetype": "namednumber",
                        "number": "56"
                    },
                    "hippiInterface": {
                        "nodetype": "namednumber",
                        "number": "57"
                    },
                    "frameRelayInterconnect": {
                        "nodetype": "namednumber",
                        "number": "58"
                    },
                    "aflane8023": {
                        "nodetype": "namednumber",
                        "number": "59"
                    },
                    "aflane8025": {
                        "nodetype": "namednumber",
                        "number": "60"
                    },
                    "cctEmul": {
                        "nodetype": "namednumber",
                        "number": "61"
                    },
                    "fastEther": {
                        "nodetype": "namednumber",
                        "number": "62"
                    },
                    "isdn": {
                        "nodetype": "namednumber",
                        "number": "63"
                    },
                    "v11": {
                        "nodetype": "namednumber",
                        "number": "64"
                    },
                    "v36": {
                        "nodetype": "namednumber",
                        "number": "65"
                    },
                    "g703at64k": {
                        "nodetype": "namednumber",
                        "number": "66"
                    },
                    "g703at2mb": {
                        "nodetype": "namednumber",
                        "number": "67"
                    },
                    "qllc": {
                        "nodetype": "namednumber",
                        "number": "68"
                    },
                    "fastEtherFX": {
                        "nodetype": "namednumber",
                        "number": "69"
                    },
                    "channel": {
                        "nodetype": "namednumber",
                        "number": "70"
                    },
                    "ieee80211": {
                        "nodetype": "namednumber",
                        "number": "71"
                    },
                    "ibm370parChan": {
                        "nodetype": "namednumber",
                        "number": "72"
                    },
                    "escon": {
                        "nodetype": "namednumber",
                        "number": "73"
                    },
                    "dlsw": {
                        "nodetype": "namednumber",
                        "number": "74"
                    },
                    "isdns": {
                        "nodetype": "namednumber",
                        "number": "75"
                    },
                    "isdnu": {
                        "nodetype": "namednumber",
                        "number": "76"
                    },
                    "lapd": {
                        "nodetype": "namednumber",
                        "number": "77"
                    },
                    "ipSwitch": {
                        "nodetype": "namednumber",
                        "number": "78"
                    },
                    "rsrb": {
                        "nodetype": "namednumber",
                        "number": "79"
                    },
                    "atmLogical": {
                        "nodetype": "namednumber",
                        "number": "80"
                    },
                    "ds0": {
                        "nodetype": "namednumber",
                        "number": "81"
                    },
                    "ds0Bundle": {
                        "nodetype": "namednumber",
                        "number": "82"
                    },
                    "bsc": {
                        "nodetype": "namednumber",
                        "number": "83"
                    },
                    "async": {
                        "nodetype": "namednumber",
                        "number": "84"
                    },
                    "cnr": {
                        "nodetype": "namednumber",
                        "number": "85"
                    },
                    "iso88025Dtr": {
                        "nodetype": "namednumber",
                        "number": "86"
                    },
                    "eplrs": {
                        "nodetype": "namednumber",
                        "number": "87"
                    },
                    "arap": {
                        "nodetype": "namednumber",
                        "number": "88"
                    },
                    "propCnls": {
                        "nodetype": "namednumber",
                        "number": "89"
                    },
                    "hostPad": {
                        "nodetype": "namednumber",
                        "number": "90"
                    },
                    "termPad": {
                        "nodetype": "namednumber",
                        "number": "91"
                    },
                    "frameRelayMPI": {
                        "nodetype": "namednumber",
                        "number": "92"
                    },
                    "x213": {
                        "nodetype": "namednumber",
                        "number": "93"
                    },
                    "adsl": {
                        "nodetype": "namednumber",
                        "number": "94"
                    },
                    "radsl": {
                        "nodetype": "namednumber",
                        "number": "95"
                    },
                    "sdsl": {
                        "nodetype": "namednumber",
                        "number": "96"
                    },
                    "vdsl": {
                        "nodetype": "namednumber",
                        "number": "97"
                    },
                    "iso88025CRFPInt": {
                        "nodetype": "namednumber",
                        "number": "98"
                    },
                    "myrinet": {
                        "nodetype": "namednumber",
                        "number": "99"
                    },
                    "voiceEM": {
                        "nodetype": "namednumber",
                        "number": "100"
                    },
                    "voiceFXO": {
                        "nodetype": "namednumber",
                        "number": "101"
                    },
                    "voiceFXS": {
                        "nodetype": "namednumber",
                        "number": "102"
                    },
                    "voiceEncap": {
                        "nodetype": "namednumber",
                        "number": "103"
                    },
                    "voiceOverIp": {
                        "nodetype": "namednumber",
                        "number": "104"
                    },
                    "atmDxi": {
                        "nodetype": "namednumber",
                        "number": "105"
                    },
                    "atmFuni": {
                        "nodetype": "namednumber",
                        "number": "106"
                    },
                    "atmIma": {
                        "nodetype": "namednumber",
                        "number": "107"
                    },
                    "pppMultilinkBundle": {
                        "nodetype": "namednumber",
                        "number": "108"
                    },
                    "ipOverCdlc": {
                        "nodetype": "namednumber",
                        "number": "109"
                    },
                    "ipOverClaw": {
                        "nodetype": "namednumber",
                        "number": "110"
                    },
                    "stackToStack": {
                        "nodetype": "namednumber",
                        "number": "111"
                    },
                    "virtualIpAddress": {
                        "nodetype": "namednumber",
                        "number": "112"
                    },
                    "mpc": {
                        "nodetype": "namednumber",
                        "number": "113"
                    },
                    "ipOverAtm": {
                        "nodetype": "namednumber",
                        "number": "114"
                    },
                    "iso88025Fiber": {
                        "nodetype": "namednumber",
                        "number": "115"
                    },
                    "tdlc": {
                        "nodetype": "namednumber",
                        "number": "116"
                    },
                    "gigabitEthernet": {
                        "nodetype": "namednumber",
                        "number": "117"
                    },
                    "hdlc": {
                        "nodetype": "namednumber",
                        "number": "118"
                    },
                    "lapf": {
                        "nodetype": "namednumber",
                        "number": "119"
                    },
                    "v37": {
                        "nodetype": "namednumber",
                        "number": "120"
                    },
                    "x25mlp": {
                        "nodetype": "namednumber",
                        "number": "121"
                    },
                    "x25huntGroup": {
                        "nodetype": "namednumber",
                        "number": "122"
                    },
                    "trasnpHdlc": {
                        "nodetype": "namednumber",
                        "number": "123"
                    },
                    "interleave": {
                        "nodetype": "namednumber",
                        "number": "124"
                    },
                    "fast": {
                        "nodetype": "namednumber",
                        "number": "125"
                    },
                    "ip": {
                        "nodetype": "namednumber",
                        "number": "126"
                    },
                    "docsCableMaclayer": {
                        "nodetype": "namednumber",
                        "number": "127"
                    },
                    "docsCableDownstream": {
                        "nodetype": "namednumber",
                        "number": "128"
                    },
                    "docsCableUpstream": {
                        "nodetype": "namednumber",
                        "number": "129"
                    },
                    "a12MppSwitch": {
                        "nodetype": "namednumber",
                        "number": "130"
                    },
                    "tunnel": {
                        "nodetype": "namednumber",
                        "number": "131"
                    },
                    "coffee": {
                        "nodetype": "namednumber",
                        "number": "132"
                    },
                    "ces": {
                        "nodetype": "namednumber",
                        "number": "133"
                    },
                    "atmSubInterface": {
                        "nodetype": "namednumber",
                        "number": "134"
                    },
                    "l2vlan": {
                        "nodetype": "namednumber",
                        "number": "135"
                    },
                    "l3ipvlan": {
                        "nodetype": "namednumber",
                        "number": "136"
                    },
                    "l3ipxvlan": {
                        "nodetype": "namednumber",
                        "number": "137"
                    },
                    "digitalPowerline": {
                        "nodetype": "namednumber",
                        "number": "138"
                    },
                    "mediaMailOverIp": {
                        "nodetype": "namednumber",
                        "number": "139"
                    },
                    "dtm": {
                        "nodetype": "namednumber",
                        "number": "140"
                    },
                    "dcn": {
                        "nodetype": "namednumber",
                        "number": "141"
                    },
                    "ipForward": {
                        "nodetype": "namednumber",
                        "number": "142"
                    },
                    "msdsl": {
                        "nodetype": "namednumber",
                        "number": "143"
                    },
                    "ieee1394": {
                        "nodetype": "namednumber",
                        "number": "144"
                    },
                    "if-gsn": {
                        "nodetype": "namednumber",
                        "number": "145"
                    },
                    "dvbRccMacLayer": {
                        "nodetype": "namednumber",
                        "number": "146"
                    },
                    "dvbRccDownstream": {
                        "nodetype": "namednumber",
                        "number": "147"
                    },
                    "dvbRccUpstream": {
                        "nodetype": "namednumber",
                        "number": "148"
                    },
                    "atmVirtual": {
                        "nodetype": "namednumber",
                        "number": "149"
                    },
                    "mplsTunnel": {
                        "nodetype": "namednumber",
                        "number": "150"
                    },
                    "srp": {
                        "nodetype": "namednumber",
                        "number": "151"
                    },
                    "voiceOverAtm": {
                        "nodetype": "namednumber",
                        "number": "152"
                    },
                    "voiceOverFrameRelay": {
                        "nodetype": "namednumber",
                        "number": "153"
                    },
                    "idsl": {
                        "nodetype": "namednumber",
                        "number": "154"
                    },
                    "compositeLink": {
                        "nodetype": "namednumber",
                        "number": "155"
                    },
                    "ss7SigLink": {
                        "nodetype": "namednumber",
                        "number": "156"
                    },
                    "propWirelessP2P": {
                        "nodetype": "namednumber",
                        "number": "157"
                    },
                    "frForward": {
                        "nodetype": "namednumber",
                        "number": "158"
                    },
                    "rfc1483": {
                        "nodetype": "namednumber",
                        "number": "159"
                    },
                    "usb": {
                        "nodetype": "namednumber",
                        "number": "160"
                    },
                    "ieee8023adLag": {
                        "nodetype": "namednumber",
                        "number": "161"
                    },
                    "bgppolicyaccounting": {
                        "nodetype": "namednumber",
                        "number": "162"
                    },
                    "frf16MfrBundle": {
                        "nodetype": "namednumber",
                        "number": "163"
                    },
                    "h323Gatekeeper": {
                        "nodetype": "namednumber",
                        "number": "164"
                    },
                    "h323Proxy": {
                        "nodetype": "namednumber",
                        "number": "165"
                    },
                    "mpls": {
                        "nodetype": "namednumber",
                        "number": "166"
                    },
                    "mfSigLink": {
                        "nodetype": "namednumber",
                        "number": "167"
                    },
                    "hdsl2": {
                        "nodetype": "namednumber",
                        "number": "168"
                    },
                    "shdsl": {
                        "nodetype": "namednumber",
                        "number": "169"
                    },
                    "ds1FDL": {
                        "nodetype": "namednumber",
                        "number": "170"
                    },
                    "pos": {
                        "nodetype": "namednumber",
                        "number": "171"
                    },
                    "dvbAsiIn": {
                        "nodetype": "namednumber",
                        "number": "172"
                    },
                    "dvbAsiOut": {
                        "nodetype": "namednumber",
                        "number": "173"
                    },
                    "plc": {
                        "nodetype": "namednumber",
                        "number": "174"
                    },
                    "nfas": {
                        "nodetype": "namednumber",
                        "number": "175"
                    },
                    "tr008": {
                        "nodetype": "namednumber",
                        "number": "176"
                    },
                    "gr303RDT": {
                        "nodetype": "namednumber",
                        "number": "177"
                    },
                    "gr303IDT": {
                        "nodetype": "namednumber",
                        "number": "178"
                    },
                    "isup": {
                        "nodetype": "namednumber",
                        "number": "179"
                    },
                    "propDocsWirelessMaclayer": {
                        "nodetype": "namednumber",
                        "number": "180"
                    },
                    "propDocsWirelessDownstream": {
                        "nodetype": "namednumber",
                        "number": "181"
                    },
                    "propDocsWirelessUpstream": {
                        "nodetype": "namednumber",
                        "number": "182"
                    },
                    "hiperlan2": {
                        "nodetype": "namednumber",
                        "number": "183"
                    },
                    "propBWAp2Mp": {
                        "nodetype": "namednumber",
                        "number": "184"
                    },
                    "sonetOverheadChannel": {
                        "nodetype": "namednumber",
                        "number": "185"
                    },
                    "digitalWrapperOverheadChannel": {
                        "nodetype": "namednumber",
                        "number": "186"
                    },
                    "aal2": {
                        "nodetype": "namednumber",
                        "number": "187"
                    },
                    "radioMAC": {
                        "nodetype": "namednumber",
                        "number": "188"
                    },
                    "atmRadio": {
                        "nodetype": "namednumber",
                        "number": "189"
                    },
                    "imt": {
                        "nodetype": "namednumber",
                        "number": "190"
                    },
                    "mvl": {
                        "nodetype": "namednumber",
                        "number": "191"
                    },
                    "reachDSL": {
                        "nodetype": "namednumber",
                        "number": "192"
                    },
                    "frDlciEndPt": {
                        "nodetype": "namednumber",
                        "number": "193"
                    },
                    "atmVciEndPt": {
                        "nodetype": "namednumber",
                        "number": "194"
                    },
                    "opticalChannel": {
                        "nodetype": "namednumber",
                        "number": "195"
                    },
                    "opticalTransport": {
                        "nodetype": "namednumber",
                        "number": "196"
                    },
                    "propAtm": {
                        "nodetype": "namednumber",
                        "number": "197"
                    },
                    "voiceOverCable": {
                        "nodetype": "namednumber",
                        "number": "198"
                    },
                    "infiniband": {
                        "nodetype": "namednumber",
                        "number": "199"
                    },
                    "teLink": {
                        "nodetype": "namednumber",
                        "number": "200"
                    },
                    "q2931": {
                        "nodetype": "namednumber",
                        "number": "201"
                    },
                    "virtualTg": {
                        "nodetype": "namednumber",
                        "number": "202"
                    },
                    "sipTg": {
                        "nodetype": "namednumber",
                        "number": "203"
                    },
                    "sipSig": {
                        "nodetype": "namednumber",
                        "number": "204"
                    },
                    "docsCableUpstreamChannel": {
                        "nodetype": "namednumber",
                        "number": "205"
                    },
                    "econet": {
                        "nodetype": "namednumber",
                        "number": "206"
                    },
                    "pon155": {
                        "nodetype": "namednumber",
                        "number": "207"
                    },
                    "pon622": {
                        "nodetype": "namednumber",
                        "number": "208"
                    },
                    "bridge": {
                        "nodetype": "namednumber",
                        "number": "209"
                    },
                    "linegroup": {
                        "nodetype": "namednumber",
                        "number": "210"
                    },
                    "voiceEMFGD": {
                        "nodetype": "namednumber",
                        "number": "211"
                    },
                    "voiceFGDEANA": {
                        "nodetype": "namednumber",
                        "number": "212"
                    },
                    "voiceDID": {
                        "nodetype": "namednumber",
                        "number": "213"
                    },
                    "mpegTransport": {
                        "nodetype": "namednumber",
                        "number": "214"
                    },
                    "sixToFour": {
                        "nodetype": "namednumber",
                        "number": "215"
                    },
                    "gtp": {
                        "nodetype": "namednumber",
                        "number": "216"
                    },
                    "pdnEtherLoop1": {
                        "nodetype": "namednumber",
                        "number": "217"
                    },
                    "pdnEtherLoop2": {
                        "nodetype": "namednumber",
                        "number": "218"
                    },
                    "opticalChannelGroup": {
                        "nodetype": "namednumber",
                        "number": "219"
                    },
                    "homepna": {
                        "nodetype": "namednumber",
                        "number": "220"
                    },
                    "gfp": {
                        "nodetype": "namednumber",
                        "number": "221"
                    },
                    "ciscoISLvlan": {
                        "nodetype": "namednumber",
                        "number": "222"
                    },
                    "actelisMetaLOOP": {
                        "nodetype": "namednumber",
                        "number": "223"
                    },
                    "fcipLink": {
                        "nodetype": "namednumber",
                        "number": "224"
                    },
                    "rpr": {
                        "nodetype": "namednumber",
                        "number": "225"
                    },
                    "qam": {
                        "nodetype": "namednumber",
                        "number": "226"
                    },
                    "lmp": {
                        "nodetype": "namednumber",
                        "number": "227"
                    },
                    "cblVectaStar": {
                        "nodetype": "namednumber",
                        "number": "228"
                    },
                    "docsCableMCmtsDownstream": {
                        "nodetype": "namednumber",
                        "number": "229"
                    },
                    "adsl2": {
                        "nodetype": "namednumber",
                        "number": "230"
                    },
                    "macSecControlledIF": {
                        "nodetype": "namednumber",
                        "number": "231"
                    },
                    "macSecUncontrolledIF": {
                        "nodetype": "namednumber",
                        "number": "232"
                    },
                    "aviciOpticalEther": {
                        "nodetype": "namednumber",
                        "number": "233"
                    },
                    "atmbond": {
                        "nodetype": "namednumber",
                        "number": "234"
                    },
                    "voiceFGDOS": {
                        "nodetype": "namednumber",
                        "number": "235"
                    },
                    "mocaVersion1": {
                        "nodetype": "namednumber",
                        "number": "236"
                    },
                    "ieee80216WMAN": {
                        "nodetype": "namednumber",
                        "number": "237"
                    },
                    "adsl2plus": {
                        "nodetype": "namednumber",
                        "number": "238"
                    },
                    "dvbRcsMacLayer": {
                        "nodetype": "namednumber",
                        "number": "239"
                    },
                    "dvbTdm": {
                        "nodetype": "namednumber",
                        "number": "240"
                    },
                    "dvbRcsTdma": {
                        "nodetype": "namednumber",
                        "number": "241"
                    },
                },
            },
            "access": "readonly",
            "description":
                """The type of interface, distinguished according to
the physical/link protocol(s) immediately `below'
the network layer in the protocol stack.""",
        },  # column
        "ifMtu": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.4",
            "status": "current",
            "syntax": {
                "type": {"module": "", "name": "Integer32"},
            },
            "access": "readonly",
            "description":
                """The size of the largest datagram which can be
sent/received on the interface, specified in
octets.  For interfaces that are used for
transmitting network datagrams, this is the size
of the largest network datagram that can be sent
on the interface.""",
        },  # column
        "ifSpeed": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.5",
            "status": "current",
            "syntax": {
                "type": {"module": "RFC1155-SMI", "name": "Gauge"},
            },
            "access": "readonly",
            "description":
                """An estimate of the interface's current bandwidth
in bits per second.  For interfaces which do not
vary in bandwidth or for those where no accurate
estimation can be made, this object should contain
the nominal bandwidth.""",
        },  # column
        "ifPhysAddress": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.6",
            "status": "current",
            "syntax": {
                "type": {"module": "RFC1213-MIB", "name": "PhysAddress"},
            },
            "access": "readonly",
            "description":
                """The interface's address at the protocol layer
immediately `below' the network layer in the
protocol stack.  For interfaces which do not have
such an address (e.g., a serial line), this object
should contain an octet string of zero length.""",
        },  # column
        "ifAdminStatus": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.7",
            "status": "current",
            "syntax": {
                "type": {
                    "basetype": "Enumeration",
                    "up": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "down": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                    "testing": {
                        "nodetype": "namednumber",
                        "number": "3"
                    },
                },
            },
            "access": "readwrite",
            "description":
                """The desired state of the interface.  The
testing(3) state indicates that no operational
packets can be passed.""",
        },  # column
        "ifOperStatus": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.8",
            "status": "current",
            "syntax": {
                "type": {
                    "basetype": "Enumeration",
                    "up": {
                        "nodetype": "namednumber",
                        "number": "1"
                    },
                    "down": {
                        "nodetype": "namednumber",
                        "number": "2"
                    },
                    "testing": {
                        "nodetype": "namednumber",
                        "number": "3"
                    },
                    "unknown": {
                        "nodetype": "namednumber",
                        "number": "4"
                    },
                    "dormant": {
                        "nodetype": "namednumber",
                        "number": "5"
                    },
                    "notPresent": {
                        "nodetype": "namednumber",
                        "number": "6"
                    },
                    "lowerLayerDown": {
                        "nodetype": "namednumber",
                        "number": "7"
                    },
                },
            },
            "access": "readonly",
            "description":
                """The current operational state of the interface.
The testing(3) state indicates that no operational
packets can be passed.""",
        },  # column
        "ifLastChange": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.9",
            "status": "current",
            "syntax": {
                "type": {"module": "SNMPv2-SMI", "name": "TimeTicks"},
            },
            "access": "readonly",
            "description":
                """The value of sysUpTime at the time the interface
entered its current operational state.  If the
current state was entered prior to the last re-
initialization of the local network management
subsystem, then this object contains a zero
value.""",
        },  # column
        "ifInOctets": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.10",
            "status": "current",
            "syntax": {
                "type": {"module": "RFC1155-SMI", "name": "Counter"},
            },
            "access": "readonly",
            "description":
                """The total number of octets received on the
interface, including framing characters.""",
        },  # column
        "ifInUcastPkts": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.11",
            "status": "current",
            "syntax": {
                "type": {"module": "RFC1155-SMI", "name": "Counter"},
            },
            "access": "readonly",
            "description":
                """The number of subnetwork-unicast packets
delivered to a higher-layer protocol.""",
        },  # column
        "ifInNUcastPkts": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.12",
            "status": "current",
            "syntax": {
                "type": {"module": "RFC1155-SMI", "name": "Counter"},
            },
            "access": "readonly",
            "description":
                """The number of non-unicast (i.e., subnetwork-
broadcast or subnetwork-multicast) packets
delivered to a higher-layer protocol.""",
        },  # column
        "ifInDiscards": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.13",
            "status": "current",
            "syntax": {
                "type": {"module": "RFC1155-SMI", "name": "Counter"},
            },
            "access": "readonly",
            "description":
                """The number of inbound packets which were chosen
to be discarded even though no errors had been
detected to prevent their being deliverable to a
higher-layer protocol.  One possible reason for
discarding such a packet could be to free up
buffer space.""",
        },  # column
        "ifInErrors": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.14",
            "status": "current",
            "syntax": {
                "type": {"module": "RFC1155-SMI", "name": "Counter"},
            },
            "access": "readonly",
            "description":
                """The number of inbound packets that contained
errors preventing them from being deliverable to a
higher-layer protocol.""",
        },  # column
        "ifInUnknownProtos": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.15",
            "status": "current",
            "syntax": {
                "type": {"module": "RFC1155-SMI", "name": "Counter"},
            },
            "access": "readonly",
            "description":
                """The number of packets received via the interface
which were discarded because of an unknown or
unsupported protocol.""",
        },  # column
        "ifOutOctets": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.16",
            "status": "current",
            "syntax": {
                "type": {"module": "RFC1155-SMI", "name": "Counter"},
            },
            "access": "readonly",
            "description":
                """The total number of octets transmitted out of the
interface, including framing characters.""",
        },  # column
        "ifOutUcastPkts": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.17",
            "status": "current",
            "syntax": {
                "type": {"module": "RFC1155-SMI", "name": "Counter"},
            },
            "access": "readonly",
            "description":
                """The total number of packets that higher-level
protocols requested be transmitted to a
subnetwork-unicast address, including those that
were discarded or not sent.""",
        },  # column
        "ifOutNUcastPkts": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.18",
            "status": "current",
            "syntax": {
                "type": {"module": "RFC1155-SMI", "name": "Counter"},
            },
            "access": "readonly",
            "description":
                """The total number of packets that higher-level
protocols requested be transmitted to a non-
unicast (i.e., a subnetwork-broadcast or
subnetwork-multicast) address, including those
that were discarded or not sent.""",
        },  # column
        "ifOutDiscards": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.19",
            "status": "current",
            "syntax": {
                "type": {"module": "RFC1155-SMI", "name": "Counter"},
            },
            "access": "readonly",
            "description":
                """The number of outbound packets which were chosen
to be discarded even though no errors had been
detected to prevent their being transmitted.  One
possible reason for discarding such a packet could
be to free up buffer space.""",
        },  # column
        "ifOutErrors": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.20",
            "status": "current",
            "syntax": {
                "type": {"module": "RFC1155-SMI", "name": "Counter"},
            },
            "access": "readonly",
            "description":
                """The number of outbound packets that could not be
transmitted because of errors.""",
        },  # column
        "ifOutQLen": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.21",
            "status": "current",
            "syntax": {
                "type": {"module": "RFC1155-SMI", "name": "Gauge"},
            },
            "access": "readonly",
            "description":
                """The length of the output packet queue (in
packets).""",
        },  # column
        "ifSpecific": {
            "nodetype": "column",
            "moduleName": "RFC1213-MIB",
            "oid": "1.3.6.1.2.1.2.2.1.22",
            "status": "current",
            "syntax": {
                "type": {"module": "", "name": "ObjectIdentifier"},
            },
            "access": "readonly",
            "description":
                """A reference to MIB definitions specific to the
particular media being used to realize the
interface.  For example, if the interface is
realized by an ethernet, then the value of this
object refers to a document defining objects
specific to ethernet.  If this information is not
present, its value should be set to the OBJECT
IDENTIFIER { 0 0 }, which is a syntatically valid
object identifier, and any conformant
implementation of ASN.1 and BER must be able to
generate and recognize this value.""",
        },  # column
    },  # nodes

}
