options = {
    'list_items_network_vars': [
        'name',
        'forward_rate_all',
        'return_rate_all',
        'up_stations',
        'down_stations',
        'fault_stations',
        'up_controllers',
        'down_controllers',
    ],
    'list_items_server_vars': [
        'name',
        'ip',
        'state',
    ],
    'list_items_user_vars': [
        'name',
        'enable',
        'password',
    ],
    'list_items_alert_vars': [
        'name',
        'popup',
        'sound',
        'script',
    ],
    'list_items_dashboard_vars': [
        'name',
        'uprow',
        'hash',
    ],
    'list_items_teleport_vars': [
        'name',
        'sat_name',
    ],
    'list_items_controller_vars': [
        'name',
        'mode',
        'state',
        'rx_up_stations',
        'rx_down_stations',
        'rx_fault_stations',
        'forward_rate_all',
        'return_rate_all',
    ],
    'list_items_vno_vars': [
        'name',
        'up_stations',
        'down_stations',
        'fault_stations',
        'off_stations',
        'idle_stations',
        'forward_rate_all',
        'return_rate_all',
    ],
    'list_items_service_vars': [
        'name',
        'hub_vlan',
        'stn_vlan',
    ],
    'list_items_polrule_vars': [
        'sequence',
        'type',
        'check_type',
        'action_type',
        'not',
    ],
    'list_items_sr_controller_vars': [
        'name',
        'mode',
        'state',
    ],
    'list_items_sr_teleport_vars': [
        'name',
        'mode',
        'teleport',
    ],
    'list_items_device_vars': [
        'name',
        'state',
        'ip',
        'mode',
    ],
    'list_items_license_vars': [
        'name',
        'enable',
        'options',
        'controller',
        'set_time',
    ],
    'list_items_bal_controller_vars': [
        'name',
        'enable',
    ],
    'list_items_profile_vars': [
        'name',
        'mode2',
        'mode3',
        'mode4',
        'mode5',
        'mode6',
        'mode7',
        'mode8',
    ],
    'list_items_sw_upload_vars': [
        'name',
        'state',
        'int_state',
        'tx_controller',
        'sw_file',
        'send_time',
        'cur_repeat',
    ],
    'list_items_camera_vars': [
        'name',
        'url',
    ],
    'list_items_scheduler_vars': [
        'name',
    ],
    'list_items_qos_vars': [
        'name',
        'priority',
        'policy',
        'shaper',
    ],
    'list_items_default_station_vars': [
        'name',
        'state',
        'faults',
        'cn_on_hub',
        'station_cn',
        'tx_margin',
        'rx_errors',
        'down_times',
        'fault_times'
    ],
    'list_items_30_station_vars': [
        'name',
        'state',
        'faults',
        'serial',
        'red_serial',
        'enable',
        'mode',
        'rx_controller',
        'rx_ctr_act',
        'rx_number',
        'sw_load_id',
        'ext_gateway',
        'profile_set',
        'sw_version',
        'rx_errors',
        'cn_on_hub',
        'station_cn',
        'station_2_cn',
        'station_tx',
        'tx_margin',
        'forward_modcod',
        'return_modcod',
        'gateway_modcod',
        'return_rate_all',
        'forward_rate_all',
        'tx2_speed_all',
        'bw_rq',
        'load_avg',
        'cur_lat_deg',
        'fault_times',
        'down_times',
    ],
    'list_items_route_vars': [
        'type',
        'service',
        'source',
        'destination',
        'options',
    ],
    'list_items_rip_router_vars': [
        'service',
        'rip_next_hop',
        'lan_rx',
        'lan_default',
        'sat_rx',
        'sat_default',
        'announce',
    ],
    'list_items_port_map_vars': [
        'external_port',
        'internal_ip',
        'internal_port',
    ],
}
